### ISSUE TITLE
聊天输入框没有粘在页面底部

### ISSUE THREAD

**Issue by sugarforever** [sugarforever/chat-ollama#101]
在最新的代码实现中，聊天输入框没有粘在页面底部。当消息增长，纵向滚动条出现，输入框随消息列表滚动。

<img width="1728" alt="Screenshot 2024-03-19 at 9 11 40 PM" src="https://github.com/sugarforever/chat-ollama/assets/404421/f58140ff-ad2c-47e7-91e0-87a9fea50d93">

**Comment by satrong** [comment]
我今天来处理一下
