### ISSUE TITLE
【bug】知识库上传多个文件后，页面展示需要进行优化

### ISSUE THREAD

**Issue by qitest** [sugarforever/chat-ollama#103]
<img width="1703" alt="image" src="https://github.com/sugarforever/chat-ollama/assets/54392413/d2423a6d-4dd9-40ea-ae06-1f8df91a5e74">

上传多个文件后，页面被挤压了。

**Comment by sugarforever** [comment]
哈哈， 是个问题。尽快修复

**Comment by satrong** [comment]
@sugarforever  这个我来处理吧

**Comment by sugarforever** [comment]
#114 #125 会修复这个问题。

**Comment by sugarforever** [comment]
> <img alt="image" width="1703" src="https://private-user-images.githubusercontent.com/54392413/314363413-d2423a6d-4dd9-40ea-ae06-1f8df91a5e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNjc4MTAsIm5iZiI6MTcxMTA2NzUxMCwicGF0aCI6Ii81NDM5MjQxMy8zMTQzNjM0MTMtZDI0MjNhNmQtNGRkOS00MGVhLWFlMDYtMWY4ZGY5MWE1ZTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAwMzE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlNzUwOTU2NGU0OGZjNmUxZTgyMWRkOThjNzJmZTNhZmIzYTM4ZjY5OWY1NWIxYmIwNzJkZDM0N2FiNGNjNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Dn34IJGt-UfFlmJPhVLF25XUON_E47W5bEa31txy9SU">
> 上传多个文件后，页面被挤压了。

请拉取一下最新的代码，应该已经解决了。

**Comment by qitest** [comment]
ok
