### ISSUE TITLE
建议知识库知识支持更新管理的功能

### ISSUE THREAD

**Issue by qitest** [sugarforever/chat-ollama#104]
1. 增加已有知识库的id的内容，支持进行知识库文件的添加功能
2. 增加已有知识库的id的内容，支持进行知识库文件的删除功能

**Comment by satrong** [comment]
有 添加 和 删除 就可以不用 替换 了吧

**Comment by qitest** [comment]
> 有 添加 和 删除 就可以不用 替换 了吧

貌似也有道理
