### ISSUE TITLE
聊天界面希望能增加一个手动停止/断开的按钮,  防止本地模型重复生成

### ISSUE THREAD

**Issue by StrayDragon** [sugarforever/chat-ollama#118]
![image](https://github.com/sugarforever/chat-ollama/assets/26061593/6306c673-ee42-4ba1-a677-d81a41773d7f)

感谢作者和贡献者们, 从这学习了很多东西, 但有一个使用痛点, 希望能提供主动停止按钮,来防止本地模型重复生成, 不然目前只能等生成达到token上限或者重启服务(挠头...

**Comment by sugarforever** [comment]
@StrayDragon 最新版本已经实现该功能。请确认是否如期工作

**Comment by StrayDragon** [comment]
可以了 感谢!
