### ISSUE TITLE
nomic-embed-text 问题。

### ISSUE THREAD

**Issue by sonygod** [sugarforever/chat-ollama#12]
1.看到你的其他nomic-embed-text 的教程 ，要注册并有KEY，但你这个项目好像没有用到？

2.这个nomic-embed-text 最大支持的文件尺寸是否有限制 8000 TOKEN？还是和选择的模型有限制？

**Comment by sugarforever** [comment]
> 1.看到你的其他nomic-embed-text 的教程 ，要注册并有KEY，但你这个项目好像没有用到？
> 
> 2.这个nomic-embed-text 最大支持的文件尺寸是否有限制 8000 TOKEN？还是和选择的模型有限制？

API Key是Nomic云端服务提供的接口。模型可以本地下载运行。上下文长度参考 https://blog.nomic.ai/posts/nomic-embed-text-v1
```
We're excited to announce the release of [Nomic Embed](https://huggingface.co/nomic-ai/nomic-embed-text-v1), the first

Open source
Open data
Open training code
Fully reproducible and auditable
text embedding model with a 8192 context-length that outperforms OpenAI Ada-002 and text-embedding-3-small on both short and long context tasks.```
