### ISSUE TITLE
聊天消息较长时，向上滑动，部分消息滑动到输入框背后

### ISSUE THREAD

**Issue by sugarforever** [sugarforever/chat-ollama#123]
聊天消息较长时，向上滑动，部分消息滑动到输入框背后。

一种选择是将聊天消息列表的底部确定在输入框上沿。

<img width="1728" alt="Screenshot 2024-03-21 at 7 55 55 PM" src="https://github.com/sugarforever/chat-ollama/assets/404421/1c654735-22cb-4304-81fd-39fed94c83d6">

**Comment by sugarforever** [comment]
@satrong 有兴趣可以看看这个问题。

**Comment by satrong** [comment]
我故意这样弄的😂，大家不喜欢我就改

**Comment by satrong** [comment]
好

**Comment by satrong** [comment]
@sugarforever  这个可以关闭了
