### ISSUE TITLE
[Feature Request] Analyse chatflow integration

### ISSUE THREAD

**Issue by meokey** [sugarforever/chat-ollama#132]
just want to mention the feature that might help in some cases, analysing chatflow using `ChatSmith`, `LangFuse`, or `Lunary`. They are very helpful tools offering detailed information about the chatflow.

**Comment by sugarforever** [comment]
ChatOllama already has the LangSmith packed, so once you set the following 3 environmental variables, you should be able to track the workflow with LangSmith.
```
LANGCHAIN_TRACING_V2=true
LANGCHAIN_API_KEY=******
LANGCHAIN_PROJECT=chat-ollama
```
