### ISSUE TITLE
建议新增 通义千问千亿级别超大规模语言模型到chat ollama 中

### ISSUE THREAD

**Issue by caihengsheng** [sugarforever/chat-ollama#137]
阿里通义千问千亿级别超大规模语言模型qwen-max-1201，qwen-max，qwen-max-longcontext
现在正限时免费开放中， 建议新增到chat ollama中。qwen-turbo和qwen-plus也可考虑。

**Comment by XePope** [comment]
模型可以自行通过 ollama pull 下载的

**Comment by caihengsheng** [comment]
不知如何下载 qwen-max, qwen-ma-1201, qwen-max-longcontent 模型， 我试了 ollama pul qwen-max 错误无此文件？

**Comment by XePope** [comment]
ollama pull  qwen 下载其他版本可以使用　ollama pull qwen:7b 你上面存在拼写错误，可以通过https://ollama.com/library 获取可以下载的模型

**Comment by sugarforever** [comment]
> 不知如何下载 qwen-max, qwen-ma-1201, qwen-max-longcontent 模型， 我试了 ollama pul qwen-max 错误无此文件？

根据 https://ollama.com/library/qwen/tags 来看，Ollama目前不支持这几个模型。可以考虑去给Ollama提issue，请求支持

**Comment by caihengsheng** [comment]
Qwen 1.5 is a series of large language models by Alibaba Cloud spanning from 0.5B to 72B parameters， 我下载了ollama pull qwen:latest, qwen:72b, 72b-chat-q6_K  looks ok

**Comment by sugarforever** [comment]
> Qwen 1.5 is a series of large language models by Alibaba Cloud spanning from 0.5B to 72B parameters， 我下载了ollama pull qwen:latest, qwen:72b, 72b-chat-q6_K looks ok

这个issue目前能算是解决了吗？没有问题的话我就关闭这个issue了。

**Comment by caihengsheng** [comment]
解决了，可以关闭。

**Comment by temberature** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/3735863/87a65b3f-2854-458b-8f39-eb5254a04650)
