### ISSUE TITLE
Chat 无法使用 500 错误 Failed to parse URL from host:11434/api/chat

### ISSUE THREAD

**Issue by XePope** [sugarforever/chat-ollama#146]
ollama serve 启动 正常
qwen:7b模型终端测试 正常

前端Chat无法使用，问题如图:
![image](https://github.com/sugarforever/chat-ollama/assets/4577514/3027b737-e0e1-44db-8dc9-fa5587fde997)
![image](https://github.com/sugarforever/chat-ollama/assets/4577514/869e27d1-b28e-453c-a16c-6d08584fd663)

**Comment by satrong** [comment]
是不是缺少了 http:// ?

**Comment by XePope** [comment]
> 是不是缺少了 http:// ?

看着不像
用docker-compose启动的不是用源码。
配置方面应该没问题，页面上的各个选项数据都正常加载到了

**Comment by satrong** [comment]
@XePope  你的这个错误意思是无法解析 URL，所以我猜测会不会是在配置页面填入的 host 缺少了 `http://` 前缀？比如：
```
http://172.21.69.91:11434
```

**Comment by sugarforever** [comment]
> @XePope 你的这个错误意思是无法解析 URL，所以我猜测会不会是在配置页面填入的 host 缺少了 `http://` 前缀？比如：
> 
> ```
> http://172.21.69.91:11434
> ```

看起来像是这个问题。

另外，我记得Settings里是有host的验证的，看起来有bug。我去看看

**Comment by XePope** [comment]
确定了确实是这个问题，仅配置ip:port模型能正常加载出来，但是chat不可用。

**Comment by heiheiheibj** [comment]
你好，请问问题解决了吗，我也是404
