### ISSUE TITLE
Latest chatollama docker image can not handle moonshot as before

### ISSUE THREAD

**Issue by Xuquansheng** [sugarforever/chat-ollama#147]
chatollama-1  | Chat with Moonshot, host:
chatollama-1  | [nuxt] [request error] [unhandled] [400] 400 invalid request: agent message content is empty
chatollama-1  |   at APIError.generate (./.output/server/node_modules/openai/error.mjs:40:20)
chatollama-1  |   at OpenAI.makeStatusError (./.output/server/node_modules/openai/core.mjs:255:25)
chatollama-1  |   at OpenAI.makeRequest (./.output/server/node_modules/openai/core.mjs:298:30)
chatollama-1  |   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
chatollama-1  |   at async ./.output/server/node_modules/@langchain/openai/dist/chat_models.js:650:29
chatollama-1  |   at async RetryOperation._fn (./.output/server/node_modules/p-retry/index.js:50:12)

**Comment by Xuquansheng** [comment]
0001coder/chatollama:1711151552 can handle Moonshot correctly.

**Comment by sugarforever** [comment]
It should not be moonshot specific issue. Probably it's related to the issue addressed by the PR below.

https://github.com/sugarforever/chat-ollama/pull/155

Please pull the latest code base or docker image. It should be working now.

**Comment by Xuquansheng** [comment]
Thanks, it's working now.
