### ISSUE TITLE
上传pdf文件后，无法正常查询知识库

### ISSUE THREAD

**Issue by keirosang** [sugarforever/chat-ollama#149]
`INFO:     [25-03-2024 03:36:53] 172.18.0.2:49918 - "POST /api/v1/collections/e2c27650-2114-4664-8e6d-76d59c90386b/upsert HTTP/1.1" 200
INFO:     [25-03-2024 03:37:07] 172.18.0.2:56850 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:37:07] 172.18.0.2:56850 - "POST /api/v1/collections/e2c27650-2114-4664-8e6d-76d59c90386b/query HTTP/1.1" 400
INFO:     [25-03-2024 03:37:07] 172.18.0.2:56850 - "POST /api/v1/collections/e2c27650-2114-4664-8e6d-76d59c90386b/query HTTP/1.1" 400
INFO:     [25-03-2024 03:37:52] 172.25.224.1:14443 - "GET / HTTP/1.1" 404
INFO:     [25-03-2024 03:37:52] 172.25.224.1:14443 - "GET /favicon.ico HTTP/1.1" 404
INFO:     [25-03-2024 03:40:35] 172.25.224.1:15105 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:40:57] 172.25.224.1:15131 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:41:06] 172.25.224.1:15146 - "GET /api/v1/collections/e2c27650-2114-4664-8e6d-76d59c90386b/query HTTP/1.1" 405
INFO:     [25-03-2024 03:43:45] 172.18.0.2:51364 - "DELETE /api/v1/collections/collection_4?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:43:47] 172.25.224.1:15422 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:43:48] 172.25.224.1:15422 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:44:15] 172.18.0.2:56750 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
DEBUG:    [25-03-2024 03:44:17] Starting component PersistentLocalHnswSegment
INFO:     [25-03-2024 03:44:17] 172.18.0.2:56750 - "POST /api/v1/collections/c79f0446-621c-425c-9f95-1be8e9ac70c6/upsert HTTP/1.1" 200
INFO:     [25-03-2024 03:45:03] 172.25.224.1:15489 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:45:22] 172.18.0.2:38202 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:45:22] 172.18.0.2:38202 - "POST /api/v1/collections/c79f0446-621c-425c-9f95-1be8e9ac70c6/query HTTP/1.1" 400
INFO:     [25-03-2024 03:45:22] 172.18.0.2:38202 - "POST /api/v1/collections/c79f0446-621c-425c-9f95-1be8e9ac70c6/query HTTP/1.1" 400
INFO:     [25-03-2024 03:46:29] 172.18.0.2:56398 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:46:31] 172.18.0.2:56398 - "POST /api/v1/collections/c79f0446-621c-425c-9f95-1be8e9ac70c6/query HTTP/1.1" 400
INFO:     [25-03-2024 03:46:31] 172.18.0.2:56398 - "POST /api/v1/collections/c79f0446-621c-425c-9f95-1be8e9ac70c6/query HTTP/1.1" 400
INFO:     [25-03-2024 03:48:09] 172.18.0.2:36818 - "DELETE /api/v1/collections/collection_5?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:48:19] 172.18.0.2:53208 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
DEBUG:    [25-03-2024 03:48:22] Starting component PersistentLocalHnswSegment
INFO:     [25-03-2024 03:48:22] 172.18.0.2:53208 - "POST /api/v1/collections/8d2819b3-34d2-4d70-9c6e-d1688d5ba246/upsert HTTP/1.1" 200
INFO:     [25-03-2024 03:50:53] 172.18.0.2:59264 - "DELETE /api/v1/collections/collection_6?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:51:04] 172.18.0.2:38518 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
DEBUG:    [25-03-2024 03:51:06] Starting component PersistentLocalHnswSegment
INFO:     [25-03-2024 03:51:06] 172.18.0.2:38518 - "POST /api/v1/collections/6216abd4-32de-428d-9221-fd9d3b8f00d7/upsert HTTP/1.1" 200
INFO:     [25-03-2024 03:51:46] 172.25.224.1:15899 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:52:22] 172.18.0.2:49752 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
INFO:     [25-03-2024 03:52:23] 172.18.0.2:49752 - "POST /api/v1/collections/6216abd4-32de-428d-9221-fd9d3b8f00d7/query HTTP/1.1" 400
INFO:     [25-03-2024 03:52:23] 172.18.0.2:49752 - "POST /api/v1/collections/6216abd4-32de-428d-9221-fd9d3b8f00d7/query HTTP/1.1" 400`

chat 对话功能正常。
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/3cdde9d6-18d5-4b57-8984-b4cc37185a3c)
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/c1a2ef6d-8057-496e-974c-592487b7d904)
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/7b56f449-3a3e-4228-88b6-1dd688e0a31b)
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/a3626fd8-fd1b-4907-ac5f-3e3707ea7c21)
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/50ea816a-e339-4bf2-b8bd-a053502a9568)

上传pdf
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/c32e07f6-59c0-4ec2-838a-cc2c24d7d77e)
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/32b3cfb2-678b-4b59-b4fb-84728f14f338)
回答永远是以下内容
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/565ffd82-ccf2-47c1-91e1-a1f0fe33d3d1)
![image](https://github.com/sugarforever/chat-ollama/assets/13990776/9b85e38c-79d5-4e2a-8627-89e0f24a5c8d)

**Comment by wanghe0128** [comment]
我修改了models->chat下面的index.post.ts下图的内容，就出来了。
![Uploading image.png…]()

**Comment by sulaymanyf** [comment]
> 我修改了models->chat下面的index.post.ts下图的内容，就出来了。 ![image](https://private-user-images.githubusercontent.com/62654872/316458305-3ec3fd50-2733-460f-9645-417eb834a8a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjkzNDQsIm5iZiI6MTcxMTM2OTA0NCwicGF0aCI6Ii82MjY1NDg3Mi8zMTY0NTgzMDUtM2VjM2ZkNTAtMjczMy00NjBmLTk2NDUtNDE3ZWI4MzRhOGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDEyMTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODg3MWRlNTZkMWQ5YjBlOWIzOTVmZTM1MTZlOWZjNWVlNGRmN2RkZTcyZjA2NTk2Y2EwMzNkZWE1NzM4NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EkrTHhVNWxZoVliJ1oD4-tvOZ7REZP_VeN_I9Rthm68)

这个文件在哪里 是在docker 里面直接改的吗

**Comment by wanghe0128** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by sugarforever** [comment]
@wanghe0128 @sulaymanyf @keirosang 

根本原因是前端消息发送时的bug，API不需要修改。请参考 PR https://github.com/sugarforever/chat-ollama/pull/155

最新版本应该已经解决这个问题，请更新。

**Comment by kamly** [comment]
docker image 是有有更新？

**Comment by sugarforever** [comment]
> docker image 是否有更新？

同步更新的
