### ISSUE TITLE
【需求】是否可以拆分后端服务将SSR改为CSR模式

### ISSUE THREAD

**Issue by wuhao930406** [sugarforever/chat-ollama#152]
拆分为前后端分离的模式可以支持：

1.生产中自定义UI界面
2.给出API调用方式方便适配业务调用自定义知识库的功能

**Comment by sugarforever** [comment]
目前的实现上来说，后端API也是独立的，可以供自定义UI界面使用。目前所缺失的是API文档。你可以参考server/api目录。

**Comment by wuhao930406** [comment]
> 目前的实现上来说，后端API也是独立的，可以供自定义UI界面使用。目前所缺失的是API文档。你可以参考server/api目录。

好的，我这边使用nestjs将这个项目的后端单独拆分出来了
