### ISSUE TITLE
models->chat下面的index.post.ts页面代码存在问题，导致知识库内容检索不到。

### ISSUE THREAD

**Issue by wanghe0128** [sugarforever/chat-ollama#154]
在知识库查询时，下面图片的代码，-1的时候，query无内容，当修改为-2的时候可以查询出内容。
![1711359426000](https://github.com/sugarforever/chat-ollama/assets/62654872/18470dce-ebe7-4caf-a0ea-1df79aa03924)

**Comment by sugarforever** [comment]
这个问题我正在看。在前端的修改，导致了与后端的通信中消息messages没有正确的处理。

感谢反馈。

**Comment by satrong** [comment]
@sugarforever  是这里没过滤数据

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/4a5b0b99-7179-4fe2-b09a-e831ae6e018d)

**Comment by sugarforever** [comment]
PR https://github.com/sugarforever/chat-ollama/pull/155

**Comment by sugarforever** [comment]
> @sugarforever 是这里没过滤数据
> 
> ![图片](https://private-user-images.githubusercontent.com/5283258/316680919-4a5b0b99-7179-4fe2-b09a-e831ae6e018d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MTA0NjgsIm5iZiI6MTcxMTQxMDE2OCwicGF0aCI6Ii81MjgzMjU4LzMxNjY4MDkxOS00YTViMGI5OS03MTc5LTRmZTItYjA5YS1lODMxYWU2ZTAxOGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjVUMjM0MjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjU4NDZmYjQxMzM5OGMwOWJkZjI5ZDZkYzEwZjM0NmRiMjMxMDNjZWU3ZDI3OTIyMjMyMDllNjliZGMzMzcwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aZY9svvIwy3xpSm4TDgg9qXj2NV6SeVBYmIOP7poYI8)

是的。我加上了。

**Comment by sugarforever** [comment]
@wanghe0128 请拉取最新版本验证。应该修复了。

**Comment by sugarforever** [comment]
@wanghe0128 有时间请确认下问题是否已经修复

**Comment by wanghe0128** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
