### ISSUE TITLE
Settings部分，Ollama Host设置没有成功验证是否以http或https开头

### ISSUE THREAD

**Issue by sugarforever** [sugarforever/chat-ollama#156]
The state field used in Ollama host validation is wrong. It should be `ollamaHost` .

**Comment by sugarforever** [comment]
PR https://github.com/sugarforever/chat-ollama/pull/157

**Comment by Xuquansheng** [comment]
It's OK with http://ollama:11434, ollama is service name in docker-compose.yaml.

**Comment by Xuquansheng** [comment]
below is my docker-compose.yaml:
root@app:~/chat-ollama# more docker-compose.yaml
version: '3.1'

services:
  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama

  chromadb:
    image: chromadb/chroma
    volumes:
      - chromadb_data:/chroma/chroma/

  chatollama:
    image: 0001coder/chatollama
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
    ports:
      - "3000:3000"
    volumes:
      - chatollama_data:/app/sqlite

volumes:
  chromadb_data:
  ollama_data:
  chatollama_data:
