### ISSUE TITLE
知识库聊天输入框没有粘在页面底部

### ISSUE THREAD

**Issue by sugarforever** [sugarforever/chat-ollama#163]
Chat页面的输入框是正常地待在页面底部的。

<img width="1726" alt="Screenshot 2024-03-27 at 11 37 37 PM" src="https://github.com/sugarforever/chat-ollama/assets/404421/5db7fee8-a54a-4208-9c39-662e6f015056">

**Comment by sugarforever** [comment]
@satrong 这个issue你有时间看看吗？

**Comment by satrong** [comment]
好的

**Comment by sugarforever** [comment]
已解决
