### ISSUE TITLE
如何让模型使用中文进行对话？

### ISSUE THREAD

**Issue by xiaoxinpro** [sugarforever/chat-ollama#167]
如下图，我使用中文提问，模型却用英文回答我的问题。

![image](https://github.com/sugarforever/chat-ollama/assets/11443745/66e10327-f327-40aa-a2b4-ee1119d12fb4)

**Comment by XXpE3** [comment]
```
ollama run yi:6b-chat
```

**Comment by satrong** [comment]
可以试试阿里的 qwen 模型

**Comment by xiaoxinpro** [comment]
@XXpE3 @satrong 使用中文模型当然没问题，我是想用llama2实现中文对话，目前只能在对话开始使用 `请使用中文与我对话，`开头，但这样很麻烦，想知道有没有可以切换默认语言的方法。

**Comment by satrong** [comment]
刚试了一下，能用

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/1ed2942a-2b1f-4a73-9d67-760aee639f61)


![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/172dd04d-668c-4160-993b-84e96bca62cd)

**Comment by xiaoxinpro** [comment]
@satrong  你是用最新版本的吗？ 我是用最新docker部署的，`Create New Instruction` 点击没有反应， #168

**Comment by XXpE3** [comment]
> @satrong 你是用最新版本的吗？ 我是用最新docker部署的，`Create New Instruction` 点击没有反应， #168

我也是 Docker ，创建指令没有问题。Docker 日志里有报错吗？

**Comment by xiaoxinpro** [comment]
@satrong 指令的约束力好像不强

![image](https://github.com/sugarforever/chat-ollama/assets/11443745/8fc85794-6403-4b94-87fa-cd9ee9cce313)

**Comment by satrong** [comment]
😂

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/13b95936-9e68-4ea1-bc75-c4df1c84ca8d)

**Comment by xiaoxinpro** [comment]
好吧，也许是llama2的模型问题，感谢 @satrong 

![image](https://github.com/sugarforever/chat-ollama/assets/11443745/7a4afccf-45e6-4adb-9f88-2891f150ef94)
