### ISSUE TITLE
knowledgebases上传文件有误，控件没有target属性

### ISSUE THREAD

**Issue by bend2046** [sugarforever/chat-ollama#171]
![image](https://github.com/sugarforever/chat-ollama/assets/42745382/ec293ecd-8452-46b3-979d-6332416da34b)

**Comment by satrong** [comment]
我这边测试没报错，截图看看报什么错，顺便提供一下你的浏览器版本

**Comment by jmshtw** [comment]
我也遇到同样的问题，提示错误如下：
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'files')
    at onFileChange (index.vue:23:34)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:715:5)
    at runtime-core.esm-bundler.js:7803:45
    at Proxy.onChange (Input.vue:191:7)
    at _mergeProps.onChange._cache.<computed>._cache.<computed> (Input.vue:16:16)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at HTMLInputElement.invoker (runtime-dom.esm-bundler.js:693:5)

nodejs: v20.10.0 ; windows11;  chrome: Version 122.0.6261.129 (Official Build) (64-bit)

**Comment by satrong** [comment]
@jmshtw 好的，明天我来看下

**Comment by pulikeyati** [comment]
我也一样啊，知识库怎么操作都是：
Tips
Must upload at least one file

用的Embedding 
两个名字都试过了nomic-embed-text:latest
nomic-embed-text

![PB5RFBBF0%79VL3TKU0$B](https://github.com/sugarforever/chat-ollama/assets/70191919/14c2d852-5bd6-44ed-acb6-5cd26fadfc1c)

**Comment by sugarforever** [comment]
@jmshtw @bend2046 我用了同样的node版本，在Chrome上无法重现这个bug。

搜了一些帖子，不确定以下这个PR能不能解决问题。你们本地测试下？看看能解决不？我暂时还没有合并这个PR。
https://github.com/sugarforever/chat-ollama/pull/172

**Comment by jmshtw** [comment]
@sugarforever @satrong 我在本地尝试升级node到v20.12.0版本，测试还是同样的错误。
修改为：selectedFiles.value = e.currentTarget?.files || e.dataTransfer?.files || []; 前端代码不报错误了，但是提交保存时，tip提示Must upload at least one file。

**Comment by satrong** [comment]
@jmshtw 在那行代码的下面加一行下面的代码：

```js
console.log('files:', e.currentTarget?.files || e.dataTransfer?.files)
```

然后打开浏览器的控制台看看输出啥，帮忙看下，多谢～

**Comment by jmshtw** [comment]
@satrong 控制台输出：
files: undefined

**Comment by satrong** [comment]
@jmshtw 再把那行代码换成下面的代码

```js
console.log('event', e)
```

然后在控制台中展开打印的对象，截图给我看看，多谢

**Comment by jmshtw** [comment]
![1](https://github.com/sugarforever/chat-ollama/assets/117361423/df89b15d-c965-4031-97b7-bc7f2013c585)
![2](https://github.com/sugarforever/chat-ollama/assets/117361423/bcf9eb79-741d-4d90-898a-0929cdd2df35)

**Comment by jmshtw** [comment]
@satrong 我尝试上传多个文件，但是只会输出第一个。

**Comment by satrong** [comment]
@jmshtw  可以看下这个 https://github.com/nuxt/ui/pull/1570 ，这个问题似乎是 @nuxt/ui 的 bug

你试试将 `<UInput>` 换成原生的 `<input>` 看看

**Comment by satrong** [comment]
https://github.com/nuxt/ui/commit/92e736213b221d5ec8cfb8881fda4fc65ce7dfa0

看了 nuxt ui 的更新记录，就是3月26日这个版本改出问题了，目前官方已经修复了这个 bug 但还没发版

**Comment by satrong** [comment]
我猜测，大家出现这个问题应该是使用了 `npm` 或者 `yarn` 安装了依赖，使用 `pnpm` 应该不会有问题（因为有 pnpm-lock.yaml 锁定版本）

如果不想使用 `pnpm` 安装依赖，临时的解决方法：

将 package.json 里面的 `dependencies` 暂时手动改下：

```diff
- "@nuxt/ui": "^2.14.2",
+ "@nuxt/ui": "~2.14.2",
```

**Comment by jmshtw** [comment]
@satrong 是的，我是使用npm安装的依赖。另外，使用原生的 <input> 是可以的，如下：
<UFormGroup label="Files as Knowledge Base">
   
  <input type="file" multiple name="file" accept=".txt,.json,.md,.doc,.docx,.pdf" @change="onFileChange" />
</UFormGroup>
感谢您的付出与支持，谢谢。

**Comment by sugarforever** [comment]
@jmshtw @satrong 感谢感谢。等nuxt ui更新后，我更新一下版本。

目前合并了 PR https://github.com/sugarforever/chat-ollama/pull/172/files，将输入组件替换为了原生组件，这样应该在npm下也能正常工作了。

**Comment by sugarforever** [comment]
看看这个问题还存在不？没有问题的话就可以关闭了。
