### ISSUE TITLE
ERROR: The Compose file './docker-compose.yaml' is invalid because: Unsupported config option for services.chatollama: 'pull_policy'

### ISSUE THREAD

**Issue by iaoxuesheng** [sugarforever/chat-ollama#177]
ERROR: The Compose file './docker-compose.yaml' is invalid because:
Unsupported config option for services.chatollama: 'pull_policy'

**Comment by sugarforever** [comment]
> ERROR: The Compose file './docker-compose.yaml' is invalid because: Unsupported config option for services.chatollama: 'pull_policy'

Could you please share your OS and docker version? You can try to upgrade your Docker to the latest version and give it another try.

https://github.com/compose-spec/compose-spec/blob/master/spec.md#pull_policy
