### ISSUE TITLE
数据库准备配置

### ISSUE THREAD

**Issue by eshinexu** [sugarforever/chat-ollama#2]
## 向量数据库
	  https://hub.docker.com/r/chromadb/chroma/tags
	
	  docker pull chromadb/chroma
	  docker run -d -p 8000:8000 chromadb/chroma
	  
	  # 访问地址：http://localhost:8000

	

 ## sqlite 数据库

	 #从 .env.example 复制文件 .env
	 cp .env.example .env
	
	 #修改配置文件 .env 中的 sqlite 路径：
	 DATABASE_URL=file:/Users/xxx/chat-ollama/prisma/.sqlite/chatollama.sqlite

### 执行数据库脚本迁移
	

	  # 安装prisma
	  npm install -g prisma
	  
	  # 执行脚本迁移
	  cd prisma
	  prisma migrate dev

**Comment by sonygod** [comment]
这个数据库哪里来的？chatollama.sqlite？好像这个库没有

**Comment by sugarforever** [comment]
> 这个数据库哪里来的？chatollama.sqlite？好像这个库没有

参考最新的文档 - https://github.com/sugarforever/chat-ollama/blob/main/README.md
prisma migrate 会创建这个库

**Comment by sonygod** [comment]
thank you .补充一下 全局变量 要提前定义
export DATABASE_URL="file:/home/sonygod/projects/chat-ollama/mydatabase.db"

**Comment by satrong** [comment]
@sonygod 使用环境变量文件就可以（即 .env 文件），不需要配置终端的临时变量
