### ISSUE TITLE
用IP:port的方式设置gemini api可以chat；但是用域名反代端口，无法chat，报错说没有模型。

### ISSUE THREAD

**Issue by kaikanertan** [sugarforever/chat-ollama#205]
用IP:port的方式设置gemini api，save后可以chat。
但是用域名反代端口，chat会报没有模型。

**Comment by Rick1125** [comment]
我也是同样的问题，nginx反代后设置ollama server，无法显示model，通过端口访问就没问题。

**Comment by satrong** [comment]
是反向代理 chat-ollama 吗？

**Comment by Rick1125** [comment]
> 是反向代理 chat-ollama 吗？

是的

**Comment by satrong** [comment]
@kaikanertan  @Rick1125  这个是因为使用 nginx 代理后，nginx 默认过滤了我们自定义的 header 字段，导致服务端拿不到 settings 里面的配置。

解决方法是加一行 `underscores_in_headers on;` 配置，如下代码：

```
server {
    listen       80;
    server_name  yourdomain.com;

    underscores_in_headers on;

    location / {
      proxy_pass http://127.0.0.1:3000/;
    }
}
```

**Comment by Rick1125** [comment]
搞定了，谢谢~！

**Comment by satrong** [comment]
#330 已解决该问题
