### ISSUE TITLE
Settings页面中卡片圆角被部分遮罩

### ISSUE THREAD

**Issue by sugarforever** [sugarforever/chat-ollama#208]
<img width="1189" alt="Screenshot 2024-04-05 at 1 28 51 AM" src="https://github.com/sugarforever/chat-ollama/assets/404421/dd13e4fa-3b6c-46aa-b86c-3dd207feb13d">

如图，左上角和右上角

**Comment by satrong** [comment]
额，这个在暗模式下没察觉不到
