### ISSUE TITLE
[bug]添加url功能后在建立知识库时必须要输入url，没有针对null的情况处理

### ISSUE THREAD

**Issue by Delthin** [sugarforever/chat-ollama#220]
![屏幕截图 2024-04-06 183717](https://github.com/sugarforever/chat-ollama/assets/113776150/31d12430-0e9a-4938-9f9b-b1f25ea3da2b)
仅有pdf的情况。随便加入一个url和pdf同时上传后成功

**Comment by sugarforever** [comment]
@Delthin https://github.com/sugarforever/chat-ollama/pull/222 这个PR已经解决该问题。请尝试最新代码。

**Comment by sugarforever** [comment]
问题已解决
