### ISSUE TITLE
更新至最新的版本後(添加URL功能)，無法建立新的Knowledge Base

### ISSUE THREAD

**Issue by Rock1965** [sugarforever/chat-ollama#221]
chatollama-1  | KnowledgeBaseFile with ID:  29
chatollama-1  | URL:  http://google.com
chatollama-1  | [nuxt] [request error] [unhandled] [500] Failed to launch the browser process!
chatollama-1  | /root/.cache/puppeteer/chrome/linux-123.0.6312.105/chrome-linux64/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
chatollama-1  |
chatollama-1  |
chatollama-1  | TROUBLESHOOTING: https://pptr.dev/troubleshooting
chatollama-1  |
chatollama-1  |   at Interface.onClose (./.output/server/node_modules/@puppeteer/browsers/lib/esm/launch.js:301:24)
chatollama-1  |   at Interface.emit (node:events:526:35)
chatollama-1  |   at Interface.close (node:internal/readline/interface:527:10)
chatollama-1  |   at Socket.onend (node:internal/readline/interface:253:10)
chatollama-1  |   at Socket.emit (node:events:526:35)
chatollama-1  |   at endReadableNT (node:internal/streams/readable:1376:12)
chatollama-1  |   at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

執行環境：WSL + Docker (ollama, chatollama, chromdb)

**Comment by wgong** [comment]
I ran into this same issue, able to add URL document, but adding PDF without URL threw the following error
```
Created knowledge base LLM: 14
Warning: Required "glyf" table is not found -- trying to recover.
Creating embeddings for Ollama served model: nomic-embed-text
Creating Chroma vector store
Initializing vector store retriever
95 documents added to collection collection_14.
KnowledgeBaseFile with ID:  11
URL:  

 ERROR  [nuxt] [request error] [unhandled] [500] Protocol error (Page.navigate): Cannot navigate to invalid URL
  at Callback.<instance_members_initializer> (./node_modules/puppeteer-core/src/common/CallbackRegistry.ts:114:12)  
  at Callback (./node_modules/puppeteer-core/src/common/CallbackRegistry.ts:119:3)  
  at CallbackRegistry.create (./node_modules/puppeteer-core/src/common/CallbackRegistry.ts:27:22)  
  at Connection._rawSend (./node_modules/puppeteer-core/src/cdp/Connection.ts:120:22)  
  at CdpCDPSession.send (./node_modules/puppeteer-core/src/cdp/CDPSession.ts:95:29)  
  at navigate (./node_modules/puppeteer-core/src/cdp/Frame.ts:182:39)  
  at CdpFrame.goto (./node_modules/puppeteer-core/src/cdp/Frame.ts:147:7)  
  at CdpFrame.<anonymous> (./node_modules/puppeteer-core/src/util/decorators.ts:63:21)  
  at CdpPage.goto (./node_modules/puppeteer-core/src/api/Page.ts:1581:35)  
  at PuppeteerWebBaseLoader._scrape (./node_modules/langchain/dist/document_loaders/web/puppeteer.js:46:20)

Ollama:  { host: 'http://127.0.0.1:11434', username: null, password: null }

```

**Comment by caihengsheng** [comment]
I have same issue when I update Knowledge Base add file:
chatollama-1  | Error: Failed to launch the browser process!
chatollama-1  | /root/.cache/puppeteer/chrome/linux-123.0.6312.105/chrome-linux64/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
chatollama-1  |
chatollama-1  |
chatollama-1  | TROUBLESHOOTING: https://pptr.dev/troubleshooting

**Comment by sugarforever** [comment]
@Rock1965 @wgong @caihengsheng Please try with the latest code base or docker image. This PR https://github.com/sugarforever/chat-ollama/pull/222 has addressed the issue.

**Comment by caihengsheng** [comment]
I just test,  fixed it for small size PDF file, but not fix for large size PDF file:
chatollama-1  | 2 documents added to collection collection_33.
chatollama-1  | Knowledge base file created with ID:  45
chatollama-1  | URL:
chatollama-1  | Error: Failed to launch the browser process!
chatollama-1  | /root/.cache/puppeteer/chrome/linux-123.0.6312.105/chrome-linux64/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory
chatollama-1  |
chatollama-1  |
chatollama-1  | TROUBLESHOOTING: https://pptr.dev/troubleshooting

**Comment by satrong** [comment]
@sugarforever  好像跟 linux 环境下的 pptr 安装有关

**Comment by satrong** [comment]
我刚在 Ubuntu 22.04 中测试了，未能重现，不确定是不是在 wsl 中才能重现

**Comment by Rock1965** [comment]
> @Rock1965 @wgong @caihengsheng Please try with the latest code base or docker image. This PR #222 has addressed the issue.

The problem is not completely resolved. When a new knowledge base has a URL, or when knowledge is modified (even if there is no URL), there are still the same errors, but adding or modifying the PDF to the knowledge base is successful.

**Comment by sugarforever** [comment]
@Rock1965 Please confirm with https://github.com/sugarforever/chat-ollama/pull/234 the issue got addressed.

**Comment by caihengsheng** [comment]
It looks good!

**Comment by Rock1965** [comment]
> @Rock1965 Please confirm with #234 the issue got addressed.

Besides still not being able to use a URL as a Knowledge Base source (with the same error as before: [nuxt] [request error] [unhandled] [500] Failed to launch the browser process! /root/.cache/puppeteer/chrome/linux-1095492/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory), all other issues have been fixed. 

Thanks.
