### ISSUE TITLE
复制聊天记录提示：Permission denied

### ISSUE THREAD

**Issue by huicewang** [sugarforever/chat-ollama#243]
![image](https://github.com/sugarforever/chat-ollama/assets/19237481/1c4c8767-ebfe-40b2-b8ed-7c5be5fd2cd9)

**Comment by huicewang** [comment]
在linux的docker容器环境中报错，但是windows开发环境是正常的

**Comment by sugarforever** [comment]
容器内报什么错误能看到吗？方便贴到这里我们看看吗

**Comment by huicewang** [comment]
容器没有报错，跟踪代码是这里报错
![image](https://github.com/sugarforever/chat-ollama/assets/19237481/53ba7909-28d6-42cb-ad77-b1e247fc0ad3)

**Comment by satrong** [comment]
这个是JS没有获取到写入剪切板的权限，你用的是什么浏览器？

**Comment by huicewang** [comment]
Chrome浏览器，但是项目在本地开发环境可以正常复制





------------------ 原始邮件 ------------------
发件人: 左禾右惠 ***@***.***&gt;
发送时间: 2024年4月10日 07:19
收件人: sugarforever/chat-ollama ***@***.***&gt;
抄送: huicewang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [sugarforever/chat-ollama] 复制聊天记录提示：Permission denied (Issue #243)





 
这个是JS没有获取到写入剪切板的权限，你用的是什么浏览器？

**Comment by satrong** [comment]
有可能是本地开发环境使用的是 localhost 或者 127.0.0.1 所以浏览器给了写入权限，而 docker 环境使用的是非 https 的域名导致无法使用剪切版。

这个问题我再调整一下
