### ISSUE TITLE
基于知识库聊天返回的 source 似乎一直都是所有的知识库文件（地址）

### ISSUE THREAD

**Issue by satrong** [sugarforever/chat-ollama#253]
如图所示，source 里面的三个网址其实与我问的问题没有任何关系，我觉得不应该出现在 source 里面

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/7db057b9-05f0-4e70-9847-29b6bf851e90)

**Comment by sugarforever** [comment]
这是目前RAG策略的局限性。由于知识库里的数据较少，其他看似不相关的内容，作为“占位”，也进入了四个相关文档系列。

这是个问题，我来改进。
