### ISSUE TITLE
【功能请求】 和Zotero联动，通过文献标题检索库中pdf文件用与构建知识库

### ISSUE THREAD

**Issue by wwjCMP** [sugarforever/chat-ollama#262]
Zotero本身是广泛使用的文献管理软件。希望可以读取Zotero库中的pdf文件用于构建知识库，具体就是在构建知识库的时候通过文献标题检索zotero库中对应的pdf文件用于构建知识库。

**Comment by sugarforever** [comment]
看起来Zotero是众多知识库可以支持的数据源之一。我需要想想如何更有通用性的支持这类外部数据源？

你的应用场景中有对Zotero支持的需求吗？

**Comment by wwjCMP** [comment]
我主要是个人使用。我想所有科研工作者，甚至所有有知识管理需求的人都有这个需求吧。😂

**Comment by sugarforever** [comment]
@wwjCMP 这是一个在创建知识库的时候能支持的一种导入文档的方式。可以考虑实现，我会将这个需求创建任务放到项目kanban上。
