### ISSUE TITLE
Tools / Tool Calling Support for Langchin

### ISSUE THREAD

**Issue by briannezhad** [sugarforever/chat-ollama#266]
Will there be support for Tool calling in ChatOllama?
https://js.langchain.com/docs/integrations/chat/
<img width="939" alt="Screenshot 2024-04-13 at 5 30 31 PM" src="https://github.com/sugarforever/chat-ollama/assets/10551124/a5113ec1-e3d7-4f1e-99ce-16f9b35817b5">

```
  const chatModel = new ChatOllama({
    temperature: 0.1,
    baseUrl: import.meta.env.VITE_OLLAMA_HOST as string,
    model: 'mistral',
  }).bind({
    tools,
  });

```
Throw 
```
Object literal may only specify known properties, and 'tools' does not exist in type 'Partial<ChatOllamaCallOptions>'.ts(2353)
```

**Comment by sugarforever** [comment]
Hi, @briannezhad , are you talking about the tool call support on https://js.langchain.com/docs/integrations/chat/ollama? This is not for that class `ChatOllama`. Maybe this repo's name is quite confusing. :-)

**Comment by briannezhad** [comment]
Oops! 😁
