### ISSUE TITLE
url知识库是否可以支持 RecursiveUrlLoader

### ISSUE THREAD

**Issue by GuSanle** [sugarforever/chat-ollama#278]
url知识库是否可以支持RecursiveUrlLoader？
langchain官方也支持这个 https://js.langchain.com/docs/integrations/document_loaders/web_loaders/recursive_url_loader。
有没有了解过langchain官方的rag，https://github.com/langchain-ai/chat-langchainjs/tree/main
不过也挺弱的。

**Comment by sugarforever** [comment]
`RecursiveUrlLoader` 完全可以支持。有兴趣开个PR吗？

官方这个RAG有看过，是个很基本的实现。

**Comment by sugarforever** [comment]
@GuSanle 请尝试最新版本，已在ChatOllama中启用RecursiveUrlLoader。目前只递归了一层 `maxDepth: 1`。

**Comment by meokey** [comment]
> @GuSanle 请尝试最新版本，已在ChatOllama中启用RecursiveUrlLoader。目前只递归了一层 `maxDepth: 1`。

这个功能👍 
能不能增加一个+-选项可以选择递归层数？
然后最好随着层数变动，后面能够动态显示一共会加载多少网页？（这个实现起来可能有点复杂？）

**Comment by sugarforever** [comment]
> > @GuSanle 请尝试最新版本，已在ChatOllama中启用RecursiveUrlLoader。目前只递归了一层 `maxDepth: 1`。
> 
> 这个功能👍 能不能增加一个+-选项可以选择递归层数？ 然后最好随着层数变动，后面能够动态显示一共会加载多少网页？（这个实现起来可能有点复杂？）

可以。我用单独的issue https://github.com/sugarforever/chat-ollama/issues/308 来跟进这个需求。当前这个issue就关了。

**Comment by satrong** [comment]
@sugarforever 这个功能我可以顺便一起做
