### ISSUE TITLE
选择OpenAI的embedding model创建知识库失败

### ISSUE THREAD

**Issue by sugarforever** [sugarforever/chat-ollama#286]
错误信息如图：

<img width="1131" alt="Screenshot 2024-04-17 at 1 46 25 PM" src="https://github.com/sugarforever/chat-ollama/assets/404421/fdc045f1-d2ae-4905-9d95-a398018f7ac2">

**Comment by Jakevin** [comment]
選擇 Google 也是同樣錯誤
![截圖 2024-04-18 凌晨1 33 45](https://github.com/sugarforever/chat-ollama/assets/4224127/3e6d60ee-655a-4f9b-b1f2-b71122abb274)

**Comment by sugarforever** [comment]
@Jakevin 请拉取最新版本。已修正。
