### ISSUE TITLE
[bug] ollama內的Embedding模型無法選擇

### ISSUE THREAD

**Issue by kevin5251984** [sugarforever/chat-ollama#299]
列表沒有 nomic-embed-text:latest
![截圖 2024-04-18 下午2 56 08](https://github.com/sugarforever/chat-ollama/assets/159868618/9689b3c1-5efc-4a29-a2b7-fdbf37b807f0)

key-in 後
![截圖 2024-04-18 下午2 54 27](https://github.com/sugarforever/chat-ollama/assets/159868618/92046eab-14b2-4123-a23f-09f401f59a89)

click 後，還是沒有出現
![截圖 2024-04-18 下午2 54 32](https://github.com/sugarforever/chat-ollama/assets/159868618/6ee2c6d0-0068-4df6-bc42-ac99d219af4a)

**Comment by satrong** [comment]
这是一个已知的问题，已在  #298 中修复，需要等合并。

你直接点击 Click to use embedding ，这个时候输入框其实是有值的只是没显示出来，你可以继续后面的操作

**Comment by aohanhongzhi** [comment]
@satrong 
我今天拉取最新代码，我看到 #298 合并了。但是我的还是没有nomic-embed-text:latest

![image](https://github.com/sugarforever/chat-ollama/assets/37319319/9f4836e1-7189-49f4-b9a5-80535704a5b5)

**Comment by satrong** [comment]
@aohanhongzhi ollama 的模型是从知识库里面提取的，不是从模型列表中获取的。你先创建一个知识库

**Comment by aohanhongzhi** [comment]
@satrong  选择不了的，可能bug还在，必须填写：nomic-embed-text:latest ，才会出现。

**Comment by satrong** [comment]
就是这样的
