### ISSUE TITLE
建議:自動翻譯功能，讓懂中文的人輸入中文，但是下達prompt的是其他語言

### ISSUE THREAD

**Issue by av8dtop** [sugarforever/chat-ollama#306]
這個需求是其他語言能力不夠好要跑去用翻譯再重新輸入有點麻煩，是否能提供直接翻譯功能，謝謝

**Comment by satrong** [comment]
可以通过指令来告诉模型用中文回答你的问题

**Comment by av8dtop** [comment]
> 可以通过指令来告诉模型用中文回答你的问题

你可能誤解了，我需要的是提示詞變成英文回來變成中文，回覆時是中文這個靠自訂義提示可以解決，但是prompt提示詞通常是英文是最好的，中文其實是最難理解的，尤其是繁體，所以如果寫出來的是中文，希望輸入進去的是英文，也就是自動翻譯進去，這樣就不需要訓練model有中文的部分了，因為很多model是沒有中文太多訓練的，導致中文的進度落後許多，這也是因為中文博大精深，外國人學習中文比我們學習外語來的困難幾倍的原因，如同博主在影片上都是打英文，但是對英文能力差的人打出來的中文跟英文的涵義其實落差有一點大，希望你能理解，謝謝

**Comment by satrong** [comment]
嗯，我明白你的意思了。这是个不错的建议

**Comment by wwjCMP** [comment]
直接用支持中英双语的嵌入模型就好了，有不少性能不比纯英文的差，不过不知道繁体中文性能怎么样

**Comment by av8dtop** [comment]
> 直接用支持中英双语的嵌入模型就好了，有不少性能不比纯英文的差，不过不知道繁体中文性能怎么样
確實現在有不少多國的，但是實際上越多語系model越大是必然的，現在無法突破不增大，而且未來的走向也是進入微型時代，而且現在又礙於類似程式碼到現在為止都還是以英文為主，就是因為中文的繁雜與轉譯才停止，有幾款是可以用中文寫code但是最終全部的人都還是放棄，假設以後有突破必然直接改變一切，主要還有一個原因就是model的底層都還是英文為基底，這沒辦法改變就如同code也是，這沒有對跟錯，就好像機器是大台的那是以前硬體沒辦法做到微型，現在連VR都快成熟了必然瞬間改變一個世代的潮流，還有目前普遍的認知，還是以英文的prompt的比較準，這點我不確定是否現在還是如此，但是我知道現在model增大也是多國語系的原因之一，畢竟現在都是以向量知識庫為主導模式，用神經模式一次串出無限加速的指標模式，不知道我用的中文名詞是否恰當，因為我還沒有很熟到底層，我只是比較善用表面而已，至於繁體跟簡體是沒有落差的，如果以簡體為主，我們也只是想要答案而已，而不是想要語言正確，畢竟還有翻譯功能，哈哈，目前這是我的初步認知，如果有錯還麻煩指導，謝謝

**Comment by av8dtop** [comment]
> > 直接用支持中英双语的嵌入模型就好了，有不少性能不比纯英文的差，不过不知道繁体中文性能怎么样
> 
> 確實現在有不少多國的，但是實際上越多語系model越大是必然的，現在無法突破不增大，而且未來的走向也是進入微型時代，而且現在又礙於類似程式碼到現在為止都還是以英文為主，就是因為中文的繁雜與轉譯才停止，有幾款是可以用中文寫code但是最終全部的人都還是放棄，假設以後有突破必然直接改變一切，主要還有一個原因就是model的底層都還是英文為基底，這沒辦法改變就如同code也是，這沒有對跟錯，就好像機器是大台的那是以前硬體沒辦法做到微型，現在連VR都快成熟了必然瞬間改變一個世代的潮流，還有目前普遍的認知，還是以英文的prompt的比較準，這點我不確定是否現在還是如此，但是我知道現在model增大也是多國語系的原因之一，畢竟現在都是以向量知識庫為主導模式，用神經模式一次串出無限加速的指標模式，不知道我用的中文名詞是否恰當，因為我還沒有很熟到底層，我只是比較善用表面而已，至於繁體跟簡體是沒有落差的，如果以簡體為主，我們也只是想要答案而已，而不是想要語言正確，畢竟還有翻譯功能，哈哈，目前這是我的初步認知，如果有錯還麻煩指導，謝謝

自我指正一下 用中文寫code也是用轉譯成英文code再編譯而已，還是脫離不了英文基底

**Comment by wwjCMP** [comment]
> > > 直接用支持中英双语的嵌入模型就好了，有不少性能不比纯英文的差，不过不知道繁体中文性能怎么样
> > 
> > 
> > 確實現在有不少多國的，但是實際上越多語系model越大是必然的，現在無法突破不增大，而且未來的走向也是進入微型時代，而且現在又礙於類似程式碼到現在為止都還是以英文為主，就是因為中文的繁雜與轉譯才停止，有幾款是可以用中文寫code但是最終全部的人都還是放棄，假設以後有突破必然直接改變一切，主要還有一個原因就是model的底層都還是英文為基底，這沒辦法改變就如同code也是，這沒有對跟錯，就好像機器是大台的那是以前硬體沒辦法做到微型，現在連VR都快成熟了必然瞬間改變一個世代的潮流，還有目前普遍的認知，還是以英文的prompt的比較準，這點我不確定是否現在還是如此，但是我知道現在model增大也是多國語系的原因之一，畢竟現在都是以向量知識庫為主導模式，用神經模式一次串出無限加速的指標模式，不知道我用的中文名詞是否恰當，因為我還沒有很熟到底層，我只是比較善用表面而已，至於繁體跟簡體是沒有落差的，如果以簡體為主，我們也只是想要答案而已，而不是想要語言正確，畢竟還有翻譯功能，哈哈，目前這是我的初步認知，如果有錯還麻煩指導，謝謝
> 
> 自我指正一下 用中文寫code也是用轉譯成英文code再編譯而已，還是脫離不了英文基底

我觉得这个可以结合后续可能的多模型agent功能，识别语料的语言调用不同的模型生成答案，最后调用一个中文模型对回答进行翻译。
