### ISSUE TITLE
基于知识库的问答响应缓慢：每次提问都释放并重新加载模型

### ISSUE THREAD

**Issue by expnn** [sugarforever/chat-ollama#331]
## 部署方法
- 部署 ollama
    - 使用官方脚本 安装 ollama
    - 修改 ollama 监听地址：创建文件 `/etc/systemd/system/ollama.service.d/override.conf` 内容为：
      ```
      [Service]
      Environment="OLLAMA_HOST=0.0.0.0"
      ```
   - 拉取模型
      ```bash
      ollama pull llama3:70b-instruct-q4_K_M
      ```

- 使用仓库中的 docker-compose.yaml 文件，使用 podman-compose 进行部署。
  ```bash
  podman-compose up -d
  ```
## 相关配置
浏览器打开页面后，在 `Settings` 选项卡下，选择 `Ollama Server`，Host 处填写 `http://host.containers.internal:11434`，保存后刷新页面。确定在 `Settings`/`Ollama Server`/`Chat Settings` 中的 `Default Model` 下拉选项卡中，存在 ollama 拉取的模型。证明配置成功。

## 运行
1. 不选择知识库，在`chat`选项卡中，进行问答，除了首次提问，可能因为需要加载模型，耗时较多外，其余提问后，可获得即时的响应。
2. 新增知识库，新建 chat，并确认 chat 中选中了知识库（点击chat 右上角铅笔形的图标进行该 chat session 的配置）。在这样的情况下，进行问答，每轮提问，耗时都非常长。在后台观察选卡运行情况，发现每次提问，显存都会被释放然后再次加载。不选择知识库的情况下，不会出现这样的情况。注意，测试的时候两轮对话间时间非常短，不会是因为超时模型自动释放。

**Comment by jia-zhen-yu** [comment]
同样的问题

**Comment by jia-zhen-yu** [comment]
显存足够大

**Comment by expnn** [comment]
显存足够。不使用知识库时一切正常，引入知识库后才会出现这个问题。

**Comment by sugarforever** [comment]
> ## 部署方法
> * 部署 ollama
>   
>   * 使用官方脚本 安装 ollama
>   * 修改 ollama 监听地址：创建文件 `/etc/systemd/system/ollama.service.d/override.conf` 内容为：
>     ```
>     [Service]
>     Environment="OLLAMA_HOST=0.0.0.0"
>     ```
>   * 拉取模型
>     ```shell
>     ollama pull llama3:70b-instruct-q4_K_M
>     ```
> * 使用仓库中的 docker-compose.yaml 文件，使用 podman-compose 进行部署。
>   ```shell
>   podman-compose up -d
>   ```
> 
> ## 相关配置
> 浏览器打开页面后，在 `Settings` 选项卡下，选择 `Ollama Server`，Host 处填写 `http://host.containers.internal:11434`，保存后刷新页面。确定在 `Settings`/`Ollama Server`/`Chat Settings` 中的 `Default Model` 下拉选项卡中，存在 ollama 拉取的模型。证明配置成功。
> 
> ## 运行
> 1. 不选择知识库，在`chat`选项卡中，进行问答，除了首次提问，可能因为需要加载模型，耗时较多外，其余提问后，可获得即时的响应。
> 2. 新增知识库，新建 chat，并确认 chat 中选中了知识库（点击chat 右上角铅笔形的图标进行该 chat session 的配置）。在这样的情况下，进行问答，每轮提问，耗时都非常长。在后台观察选卡运行情况，发现每次提问，显存都会被释放然后再次加载。不选择知识库的情况下，不会出现这样的情况。注意，测试的时候两轮对话间时间非常短，不会是因为超时模型自动释放。

非常感谢如此详尽的报告。从ChatOllama来说，只是调用的Ollama的聊天补全接口。我会去Ollama Discord问问看这是什么情况，需要了解一下Ollama的运行机制了。

**Comment by expnn** [comment]
是的，很可能是上游的问题。因为我部署的AnythingLLM也有这个问题。难道是需要对query做embedding，将chat模型释放了，做完query embedding后，再重新加载的？但是我显存非常充足，完全没这个必要啊。

**Comment by jiansuer** [comment]
知识库文件过多了之后完全不会按照知识库回答，并且source也不会显示，仅会按照模型自己的内容回答

**Comment by kksasa** [comment]
如何保持模型在内存中或立即卸载？

默认情况下，模型在内存中保留5分钟后会被卸载。这样做可以在您频繁请求LLM时获得更快的响应时间。但是，您可能希望在5分钟结束之前释放内存或无限期保持模型加载。使用/api/generate和/api/chat API端点的keep_alive参数来控制模型在内存中保留的时间。

keep_alive参数可以设置为：

一个持续时间字符串（例如"10m"或"24h"）
一个以秒为单位的数字（例如3600）
任何负数，将会无限期保持模型在内存中（例如-1或"-1m"）
'0'，将在生成响应后立即卸载模型
例如，要预加载模型并保留在内存中，请使用

curl <http://localhost:11434/api/generate> -d '{"model": "llama3", "keep_alive": -1}'
要卸载模型并释放内存，请使用：

curl <http://localhost:11434/api/generate> -d '{"model": "llama3", "keep_alive": 0}'
或者，您可以通过在启动Ollama服务器时设置 OLLAMA_KEEP_ALIVE 环境变量来更改所有模型加载到内存中的时间。OLLAMA_KEEP_ALIVE 变量采用与上述keep_alive参数相同的参数类型。请参考上述说明如何配置Ollama服务器以正确设置环境变量。

如果您想覆盖 OLLAMA_KEEP_ALIVE 设置，可以在/api/generate或/api/chat API端点使用 keep_alive API 参数。

如何管理服务器可以排队的最大请求数量

如果向服务器发送的请求过多，它将返回 503 错误，表示服务器过载。您可以通过设置 OLLAMA_MAX_QUEUE 来调整可以排队的请求数量。

**Comment by jiaxin11** [comment]
> 如何保持模型在内存中或立即卸载？
> 
> 默认情况下，模型在内存中保留5分钟后会被卸载。这样做可以在您频繁请求LLM时获得更快的响应时间。但是，您可能希望在5分钟结束之前释放内存或无限期保持模型加载。使用/api/generate和/api/chat API端点的keep_alive参数来控制模型在内存中保留的时间。
> 
> keep_alive参数可以设置为：
> 
> 一个持续时间字符串（例如"10m"或"24h"） 一个以秒为单位的数字（例如3600） 任何负数，将会无限期保持模型在内存中（例如-1或"-1m"） '0'，将在生成响应后立即卸载模型 例如，要预加载模型并保留在内存中，请使用
> 
> curl http://localhost:11434/api/generate -d '{"model": "llama3", "keep_alive": -1}' 要卸载模型并释放内存，请使用：
> 
> curl http://localhost:11434/api/generate -d '{"model": "llama3", "keep_alive": 0}' 或者，您可以通过在启动Ollama服务器时设置 OLLAMA_KEEP_ALIVE 环境变量来更改所有模型加载到内存中的时间。OLLAMA_KEEP_ALIVE 变量采用与上述keep_alive参数相同的参数类型。请参考上述说明如何配置Ollama服务器以正确设置环境变量。
> 
> 如果您想覆盖 OLLAMA_KEEP_ALIVE 设置，可以在/api/generate或/api/chat API端点使用 keep_alive API 参数。
> 
> 如何管理服务器可以排队的最大请求数量
> 
> 如果向服务器发送的请求过多，它将返回 503 错误，表示服务器过载。您可以通过设置 OLLAMA_MAX_QUEUE 来调整可以排队的请求数量。

配置之后并不起作用

**Comment by expnn** [comment]
[v0.1.33](https://github.com/ollama/ollama/releases/tag/v0.1.33) 即以上的 ollama 版本可以通过添加 `OLLAMA_NUM_PARALLEL`, `OLLAMA_MAX_LOADED_MODELS` 环境变量来解决这个问题了。因此可以关闭这个issue 了。

**Comment by 673092756** [comment]
> [v0.1.33](https://github.com/ollama/ollama/releases/tag/v0.1.33) 即以上的 ollama 版本可以通过添加 `OLLAMA_NUM_PARALLEL`, `OLLAMA_MAX_LOADED_MODELS` 环境变量来解决这个问题了。因此可以关闭这个issue 了。

这两配置怎么解决啊

**Comment by satrong** [comment]
这两个设置为系统环境变量就可以

> > [v0.1.33](https://github.com/ollama/ollama/releases/tag/v0.1.33) 即以上的 ollama 版本可以通过添加 `OLLAMA_NUM_PARALLEL`, `OLLAMA_MAX_LOADED_MODELS` 环境变量来解决这个问题了。因此可以关闭这个issue 了。
> 
> 这两配置怎么解决啊

**Comment by 673092756** [comment]
> 这两个设置为系统环境变量就可以
> 
> > > [v0.1.33](https://github.com/ollama/ollama/releases/tag/v0.1.33) 即以上的 ollama 版本可以通过添加 `OLLAMA_NUM_PARALLEL`, `OLLAMA_MAX_LOADED_MODELS` 环境变量来解决这个问题了。因此可以关闭这个issue 了。
> > 
> > 
> > 这两配置怎么解决啊

![image](https://github.com/user-attachments/assets/660739cc-d6a7-449d-9a4b-2dc626fa0121)
不行啊

**Comment by satrong** [comment]
可以通过下面命令检查环境变量是否生效（不确定 ubuntu 是不是这样检查）：
```
echo $OLLAMA_NUM_PARALLEL
```

**Comment by 673092756** [comment]
> 可以通过下面命令检查环境变量是否生效（不确定 ubuntu 是不是这样检查）：
> 
> ```
> echo $OLLAMA_NUM_PARALLEL
> ```

![image](https://github.com/user-attachments/assets/ef6e422f-1fcd-49f0-91de-4c5fec045cbc)
这个样子的配置是否可以啊

**Comment by jwj76** [comment]
OLLAMA MAX LOADED MODELS=4  OK

**Comment by 673092756** [comment]
> 0.6.6下改OLLAMA_MAX_LOADED_MODELS=4也不行，还是出错一次提示要加载一个模型。

你看看模型是否一样。因为开始的时候你需要加载一个模型，后面在提问的时候他会加载第二个模型，后面这两个模型会一直存在，并行跑，只要显存够就行了
