### ISSUE TITLE
搞了一天，就是进不去知识库

### ISSUE THREAD

**Issue by shenshiguan** [sugarforever/chat-ollama#333]
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/9fb7202d-006a-4188-ba6b-97dfc8cdeab9)

**Comment by shenshiguan** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/198a282a-9e08-461c-bea7-c20ac3941ffe)

**Comment by shenshiguan** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/97ae6a59-d922-4e62-af54-7d4d45eb3430)

**Comment by shenshiguan** [comment]
经过一段时间的调试，目前进入了知识库界面，但是没有可选的embedding项。接口返回的 
{
  "knowledgeBases": []
}


![image](https://github.com/sugarforever/chat-ollama/assets/32445039/48d4ec9f-9267-479e-9555-eaa8909f59f6)

**Comment by shenshiguan** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/7621081a-94c2-47cc-a864-b5e875acc82e)

这个手写了，但是上传文件可以，但是报错，查询就是500错误。

上传控制台输出：
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/5c7da067-4bf9-42e6-8b95-494fd0e0cb00)


查询错误：
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/ac676ae4-c609-42e8-ae3c-de8b92564e53)

**Comment by shenshiguan** [comment]
数据里的数据情况是这样的。
![image](https://github.com/sugarforever/chat-ollama/assets/32445039/612d508c-7d8e-4266-8572-392ae51d1ea7)

**Comment by shenshiguan** [comment]
win中File读取的文件路径有问题。

![image](https://github.com/sugarforever/chat-ollama/assets/32445039/1af98687-354d-4131-81e6-8160029c0881)

**Comment by satrong** [comment]
代码好像没有对路径做任何的处理，上传读的是文件对象

**Comment by sugarforever** [comment]
> ![image](https://private-user-images.githubusercontent.com/32445039/324518856-7621081a-94c2-47cc-a864-b5e875acc82e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTgyMDMsIm5iZiI6MTcxMzkxNzkwMywicGF0aCI6Ii8zMjQ0NTAzOS8zMjQ1MTg4NTYtNzYyMTA4MWEtOTRjMi00N2NjLWE4NjQtYjVlODc1YWNjODJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAwMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YTUzMDI3YWYyNmM4ZTY4OTgxYWRiYjIyYmM3ODRiNmFjODZhOGI4NzgwMjQxMTA1ZDIxZjZhZjgzYTMyYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hxqJBSYbeh1gq2_D6C9xAXHXO5hX3A-V4yIRkxtSrV8)
> 
> 这个手写了，但是上传文件可以，但是报错，查询就是500错误。
> 
> 上传控制台输出： ![image](https://private-user-images.githubusercontent.com/32445039/324519001-5c7da067-4bf9-42e6-8b95-494fd0e0cb00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTgyMDMsIm5iZiI6MTcxMzkxNzkwMywicGF0aCI6Ii8zMjQ0NTAzOS8zMjQ1MTkwMDEtNWM3ZGEwNjctNGJmOS00MmU2LThiOTUtNDk0ZmQwZTBjYjAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAwMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NGZlOWI2N2Y1MGQ3ZTg4MTQ2Zjk4NDExNTJlOGRjYjIxNTU1ZDc3ZTA2MGFlNTk3ZDc3YjAzNDEyOTNlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n3nttoGbh7kUwJmTqNG7Q2fa-FsclSYtttJsVVdIM2Q)
> 
> 查询错误： ![image](https://private-user-images.githubusercontent.com/32445039/324519140-ac676ae4-c609-42e8-ae3c-de8b92564e53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MTgyMDMsIm5iZiI6MTcxMzkxNzkwMywicGF0aCI6Ii8zMjQ0NTAzOS8zMjQ1MTkxNDAtYWM2NzZhZTQtYzYwOS00MmU4LWFlM2MtZGU4YjkyNTY0ZTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAwMTgyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwNDAyOTBjMTNiZWI5MDJiN2QwZDkwMDcxOTBjMWQ4ODA2OTJhZjM2YTA1NjhmYjA5YTgzNTRjNWYxNzgyODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vDVcO4GIv_1pkfplHNUUU1aL5mtmeCSyfQzK7Z88OYM)

这个错误看起来像是Chroma方面的问题。请确认Chromadb在本地正常运行在http://localhost:8000 （这是默认值）

**Comment by shenshiguan** [comment]
chromadb  没有问题


```
  const dbConfig = {
    collectionName: collectionName,
    url: "http://192.168.0.103:8000"
  };
```

![image](https://github.com/sugarforever/chat-ollama/assets/32445039/ffd813c2-15ab-458a-acf7-236fe8276d2e)

**Comment by shenshiguan** [comment]
更新源码已经解决
