### ISSUE TITLE
加载本地模型的embedding

### ISSUE THREAD

**Issue by lonerranger** [sugarforever/chat-ollama#336]
如何加载本地模型的embedding呢？目前我看提只提供了openai和gemini的embedding-001这2个。

**Comment by sugarforever** [comment]
如果需要使用本地embedding模型，先为Ollama下载该模型，比如nomic-embed-text，然后在创建知识库窗口的embedding model那里输入nomic-embed-text（这个下拉框是支持输入的）。这种用户体验的原因是，Ollama没有接口来获取embedding模型的列表，只能依靠用户输入了。

<img width="556" alt="Screenshot 2024-04-23 at 9 41 55 AM" src="https://github.com/sugarforever/chat-ollama/assets/404421/45a065a6-0f9f-45a3-89e9-f35ea82c6d14">

**Comment by satrong** [comment]
看样子这个交互还是不够容易懂

**Comment by meokey** [comment]
> 看样子这个交互还是不够容易懂

要不然分个类，“本地”和“远程”？估计很多没有跟进AI技术的普通用户没有这个意识，Ollama就是本地，或许连embedding是干什么都不了解。

还有就是流程自动化。用户只管按照自己想做的事情点个“用本地导入知识库”按钮，后台自动下载Ollama的embedding模型（配置文件里手动维护有效模型列表），自动选取

**Comment by sugarforever** [comment]
> > 看样子这个交互还是不够容易懂
> 
> 要不然分个类，“本地”和“远程”？估计很多没有跟进AI技术的普通用户没有这个意识，Ollama就是本地，或许连embedding是干什么都不了解。
> 
> 还有就是流程自动化。用户只管按照自己想做的事情点个“用本地导入知识库”按钮，后台自动下载Ollama的embedding模型（配置文件里手动维护有效模型列表），自动选取

有道理。需要思考一下这个项目的定位。是将模型的选择等参数选择交给用户，还是系统自动选择，这是个问题

**Comment by meokey** [comment]
> > > 看样子这个交互还是不够容易懂
> > 
> > 
> > 要不然分个类，“本地”和“远程”？估计很多没有跟进AI技术的普通用户没有这个意识，Ollama就是本地，或许连embedding是干什么都不了解。
> > 还有就是流程自动化。用户只管按照自己想做的事情点个“用本地导入知识库”按钮，后台自动下载Ollama的embedding模型（配置文件里手动维护有效模型列表），自动选取
> 
> 有道理。需要思考一下这个项目的定位。是将模型的选择等参数选择交给用户，还是系统自动选择，这是个问题

成年人不做选择，都要 😃 🐶 

在简化界面上，用户不做涉及技术的选择，只专注业务（知识库，会话等）。同一个页面，再设个“高级设置”按钮，把隐藏的技术选择显示出来供高级用户使用。

**Comment by sugarforever** [comment]
> > > > 看样子这个交互还是不够容易懂
> > > 
> > > 
> > > 要不然分个类，“本地”和“远程”？估计很多没有跟进AI技术的普通用户没有这个意识，Ollama就是本地，或许连embedding是干什么都不了解。
> > > 还有就是流程自动化。用户只管按照自己想做的事情点个“用本地导入知识库”按钮，后台自动下载Ollama的embedding模型（配置文件里手动维护有效模型列表），自动选取
> > 
> > 
> > 有道理。需要思考一下这个项目的定位。是将模型的选择等参数选择交给用户，还是系统自动选择，这是个问题
> 
> 成年人不做选择，都要 😃 🐶
> 
> 在简化界面上，用户不做涉及技术的选择，只专注业务（知识库，会话等）。同一个页面，再设个“高级设置”按钮，把隐藏的技术选择显示出来供高级用户使用。

这是一个很好的建议。
1. 测试，评估，总结出一套合适的参数作为默认值。
2. 以高级设置的形式，给“高级用户”进行自定义。

**Comment by satrong** [comment]
#422 中已针对 nomic-bert 家族的文本模型 处理
