### ISSUE TITLE
知识库无法获取下载的嵌入模型，应该怎么排查错误信息

### ISSUE THREAD

**Issue by xuan-lu** [sugarforever/chat-ollama#347]
![image](https://github.com/sugarforever/chat-ollama/assets/57519290/163df9aa-f3a5-4b66-865d-526dba861477)
![image](https://github.com/sugarforever/chat-ollama/assets/57519290/08a213ce-fabc-40dd-bec1-c62d5d7b84c8)

**Comment by satrong** [comment]
手动输入嵌入模型名称，保存后下次就可以选了

**Comment by xuan-lu** [comment]
噢噢，了解。谢谢
