### ISSUE TITLE
Attached Messages Count的数量是否可以放宽？

### ISSUE THREAD

**Issue by jingnorth** [sugarforever/chat-ollama#361]
目前Attached Messages Count的数量最大为50，对于需要长输出的答案少了点，是否可以放宽限制？

**Comment by satrong** [comment]
你觉得限制到多少合适？

**Comment by sugarforever** [comment]
> 你觉得限制到多少合适？

这个参数可以迁移到Nuxt Runtime Config里面，允许运行ChatOllama的用户自行配置。

我会将这个需求转换为一个issue放到项目里

**Comment by satrong** [comment]
好

**Comment by satrong** [comment]
@jingnorth  请获取最新代码，然后在 .env 文件中配置 `NUXT_PUBLIC_CHAT_MAX_ATTACHED_MESSAGES` 来修改最大附加消息的长度
