### ISSUE TITLE
通过docker安装的，如何找到本地模型存放地址和知识库的存放地址

### ISSUE THREAD

**Issue by doriszhang2020** [sugarforever/chat-ollama#380]

**Comment by satrong** [comment]
本地模型是基于 Ollama 的，你可以去查查 Ollama 的相关文档

知识库是存储在向量数据库中的，比如 ChromaDB

**Comment by doriszhang2020** [comment]
谢谢🙏



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月28日(周日) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [sugarforever/chat-ollama] 通过docker安装的，如何找到本地模型存放地址和知识库的存放地址 (Issue #380)




 
本地模型是基于 Ollama 的，你可以去查查 Ollama 的相关文档
 
知识库是存储在向量数据库中的，比如 ChromaDB
