### ISSUE TITLE
Chroma getOrCreateCollection error: Error: AttributeError("type object 'CreateCollection' has no attribute 'model_validate'"

### ISSUE THREAD

**Issue by ALiftTime** [sugarforever/chat-ollama#395]
![image](https://github.com/sugarforever/chat-ollama/assets/42958147/bf304f31-7d8c-4bb7-91b4-87df25f00702)

![image](https://github.com/sugarforever/chat-ollama/assets/42958147/e0adeae4-a8cd-4483-8a01-b34708567f75)

老师, 我来回安装了node_modules和chroma, 但是还是会报这个错,查了文档也没找到问题,求解惑 [抱拳]

**Comment by ALiftTime** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/42958147/f48a5289-ee6d-47aa-82a7-f786ca731667)
![image](https://github.com/sugarforever/chat-ollama/assets/42958147/23a1f657-4581-412c-b9d0-91b60a949461)

我看docker上chroma下载的是 0.5.1版本的, 如果直接用 pip 安装的话,版本是 0.5.0, 会不会是zheg这个原因?

**Comment by mjyoussef** [comment]
Running into a similar issue using Node.js

**Comment by zhou9110** [comment]
I also running into the same error, and found out the version of `pydantic` library on my machine is too old. Mine is in `1.10.12`, upgrade to the lastest (2.7.1) can help
You can check with this command: 
```
pip list | grep pydantic

# pydantic                                 1.10.12
```

Then upgrade the `pydantic` library and restart the chromadb server solves my issue
```
pip install pydantic --upgrade
```

我这边也遇到了同样的问题，原因是本地的Pydantic包版本太旧(1.10.12)，用pip install升级到最新之后即可解决

**Comment by sugarforever** [comment]
> I also running into the same error, and found out the version of `pydantic` library on my machine is too old. Mine is in `1.10.12`, upgrade to the lastest (2.7.1) can help You can check with this command:
> 
> ```
> pip list | grep pydantic
> 
> # pydantic                                 1.10.12
> ```
> 
> Then upgrade the `pydantic` library and restart the chromadb server solves my issue
> 
> ```
> pip install pydantic --upgrade
> ```
> 
> 我这边也遇到了同样的问题，原因是本地的Pydantic包版本太旧(1.10.12)，用pip install升级到最新之后即可解决

非常感谢，太厉害了。

能否分享你发现问题，解决问题的过程？我很好奇老版本的pydantic是如何引起的问题

**Comment by sugarforever** [comment]
@ALiftTime ^^ 尝试升级pydantic，再看看是否问题解决？

**Comment by zhou9110** [comment]
> 非常感谢，太厉害了。

你太客气了😂 
 
> 能否分享你发现问题，解决问题的过程？我很好奇老版本的pydantic是如何引起的问题

可以的，简单来说就是根据错误信息看了出错文件的代码，定位到这一句
https://github.com/chroma-core/chroma/blob/6203deb45e21d6adc1d264087ddaff2f4627c2ac/chromadb/server/fastapi/__init__.py#L561

发现里面的 `model_validate` 是继承自 `pydantic` 的 `BaseModel`, 然后翻它的文档发现最新v2版本文档里有这个属性，但是v1版本里的没有，网上基本搜不到这个问题，表示多半只跟我的本地环境有关。正好我本地安装的版本是v1，就试着升级了一下，正好运气不错让我给蒙对了

**Comment by SpecialLeon** [comment]
> 使用 Node.js 时遇到类似问题

me too, Are you solved yet?

**Comment by satrong** [comment]
@SpecialLeon It seems that the issue may not be related to Node.js, but possibly related to chromadb. 

Have you tried this solution:

> I also running into the same error, and found out the version of `pydantic` library on my machine is too old. Mine is in `1.10.12`, upgrade to the lastest (2.7.1) can help You can check with this command:
> 
> ```
> pip list | grep pydantic
> 
> # pydantic                                 1.10.12
> ```
> 
> Then upgrade the `pydantic` library and restart the chromadb server solves my issue
> 
> ```
> pip install pydantic --upgrade
> ```
> 
> 我这边也遇到了同样的问题，原因是本地的Pydantic包版本太旧(1.10.12)，用pip install升级到最新之后即可解决
