### ISSUE TITLE
创建个人知识库，embeding模型选择，无法选择本地下载的模型，请问一下这是什么原因？

### ISSUE THREAD

**Issue by BenJamesbabala** [sugarforever/chat-ollama#400]
![微信图片_20240430181508](https://github.com/sugarforever/chat-ollama/assets/10266109/278ce350-ee13-46d5-b393-d9621dd36242)
![微信图片_20240430181522](https://github.com/sugarforever/chat-ollama/assets/10266109/f876ba35-3863-4fa1-b623-ce268c892593)

已经本地下载了本地embeding模型mxbai-embed-large和nomic-embed-text。在创建个人知识库中的embeding模型选择，无法选择本地下载的模型，请问一下这是什么原因？

**Comment by gallery2016** [comment]
the same problem, nothing left in embedding list but openai and gemini

**Comment by BenJamesbabala** [comment]
找到答案，可以参考以下视频，直接在文本框输入本地模型名称。
https://www.youtube.com/watch?v=FGHbjtIxDyQ

**Comment by BenJamesbabala** [comment]
> the same problem, nothing left in embedding list but openai and gemini

找到答案，可以参考以下视频，直接在文本框输入本地模型名称。
https://www.youtube.com/watch?v=FGHbjtIxDyQ

**Comment by sugarforever** [comment]
Sorry for confusion. We haven't found a solid solution to address embedding models in Ollama, so there's no Ollama embedding model option in the drop down list.

**Comment by samzong** [comment]
> > the same problem, nothing left in embedding list but openai and gemini
> 
> 找到答案，可以参考以下视频，直接在文本框输入本地模型名称。 https://www.youtube.com/watch?v=FGHbjtIxDyQ

我发现是可编辑的，所以我直接写入反而是成功了

**Comment by satrong** [comment]
最新版里面，如果已下载 nomic-bert 家族的文本嵌入模型，则会显示在下拉列表中（已针对 nomic-bert 做了特殊处理）
