### ISSUE TITLE
docker container無法連接到本機端的ollama

### ISSUE THREAD

**Issue by avalonliberty** [sugarforever/chat-ollama#408]
我參照doc運行chatollama在docker container裏頭，但是chatollama無法正常的接到ollama

我這邊的setting是有一台電腦A，一個Server B，ollama運行在server B上而chatollama運行在server B的container裡面

然後我從A ssh進到B的3000端口去使用chatollama

<img width="838" alt="Screenshot 2024-05-01 110558" src="https://github.com/sugarforever/chat-ollama/assets/34063554/47220679-0a04-45c8-b9e5-adc3171eee86">

我確定有跑ollama serve在11434端口上面

<img width="791" alt="Screenshot 2024-05-01 110702" src="https://github.com/sugarforever/chat-ollama/assets/34063554/f56124a7-8d17-4acd-a6fd-171def40bdc9">

這是error message

<img width="881" alt="Screenshot 2024-05-01 110733" src="https://github.com/sugarforever/chat-ollama/assets/34063554/9a4f475a-5af7-4cc9-88d2-29510c3e82ad">

這是我在chatollama裏頭的設定

想請問我那邊做錯了 導致chatollama沒辦法連到ollama呢?

**Comment by liudichen** [comment]
直接用B的IP地址可能有用

**Comment by avalonliberty** [comment]
直接用B的IP不太行 因為要ollama是public accessible，問題是我去查了一下ollama的設定，也沒辦法正確地跟著跑，這樣有點難處理

**Comment by liudichen** [comment]
把11434端口暴露出来与B端口绑定然后再使用B的IP可行吗？
```
ports:
      - "3000:3000"
      - "11434:11434"
```

**Comment by avalonliberty** [comment]
我自己研究了一下，成功把ollama的端口expose出去了。結論是router那端的setting要expose出來
只是不能使用localhost來用還是讓我蠻困惑的，但是因為我不太熟網路架構
決定還是讓traffic出去繞一圈再回來使用本機端的port
