### ISSUE TITLE
国际化支持

### ISSUE THREAD

**Issue by satrong** [sugarforever/chat-ollama#411]
#403

**Comment by sugarforever** [comment]
@satrong 

许多地方的文本需要大写字母开头，比如登录注册页面的输入框label。你先调整，开合并请求到main分支。我再看看。

**Comment by Jackxwb** [comment]
搓了一个辅助工具，对修改JSON翻译文件应该有一定帮助
[https://jackxwb.github.io/chat-ollama/scripts/MergeTranslationFilesV2.html](https://jackxwb.github.io/chat-ollama/scripts/MergeTranslationFilesV2.html)

**Comment by sugarforever** [comment]
> 搓了一个辅助工具，对修改JSON翻译文件应该有一定帮助
> 
> https://jackxwb.github.io/chat-ollama/scripts/MergeTranslationFilesV2.html ![image](https://private-user-images.githubusercontent.com/34720403/327491509-169f7689-4e80-4b2e-bb9c-89affe5fbc82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjUzNDAsIm5iZiI6MTcxNDY2NTA0MCwicGF0aCI6Ii8zNDcyMDQwMy8zMjc0OTE1MDktMTY5Zjc2ODktNGU4MC00YjJlLWJiOWMtODlhZmZlNWZiYzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE1NTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMjc0MGM4ZDBlYjE2NGFmZGE1MTYxNzZlYWVjZGRjZTUyY2JkODUwZWU2YWIyMDhkY2RmZTFjMWVmNGI1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FQfA1p7tAfj3tnyrOf2fErwiQfdlMvyPKqviS2bp9sI) 提取第一步输出的纯文本后，手动修复后，放入2处的文本框，选择输出JSON即可（行数不能乱） ![image](https://private-user-images.githubusercontent.com/34720403/327492435-8ef40a16-deff-4a3f-95d1-d8a4465f58e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjUzNDAsIm5iZiI6MTcxNDY2NTA0MCwicGF0aCI6Ii8zNDcyMDQwMy8zMjc0OTI0MzUtOGVmNDBhMTYtZGVmZi00YTNmLTk1ZDEtZDhhNDQ2NWY1OGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE1NTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5NmQwZGMxNGZkZGNmNDIwZTQ5ODAzZjMzNWZjMjkyMzk2YTdkYzlkOTMyOTk4OTQ3YThiMWU0YTNmNjI2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.02jH_cHNQn7gYq90o4s3HMl8M48SVn87P1hGEoEsoxc)
> 
> 也可用来制作其他语言的翻译文件 ![image](https://private-user-images.githubusercontent.com/34720403/327494530-f9d48556-09ae-410e-87fb-54184cf72705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjUzNDAsIm5iZiI6MTcxNDY2NTA0MCwicGF0aCI6Ii8zNDcyMDQwMy8zMjc0OTQ1MzAtZjlkNDg1NTYtMDlhZS00MTBlLTg3ZmItNTQxODRjZjcyNzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE1NTA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTc1YjI4NzRjMzNjYjJlY2VkZWVlYzI5NGIxZDI4YzJjNGNlNTIwMzM1YmQ3ZTQxM2Y0YjFhZWRkNDc0MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bywuwgo9qdGTfjz9_qObscCSLeoYa9ybsixZE2qnTLk)

真高效 🥸

**Comment by Jackxwb** [comment]
当前main主分支，InstructionForm.vue文件第56行处
`title: t('Error'),
`
有替换遗漏，可以使用全局搜索(开启正则表达式支持)快速定位 `t\("[^.]*"\)|t\('[^.]*'\)`

**Comment by satrong** [comment]
我看看
