### ISSUE TITLE
oneapi第三方代理服务出现问题

### ISSUE THREAD

**Issue by carwlyjoe** [sugarforever/chat-ollama#417]
我使用相同的Endpoint和API Key在Next Web中使用是可以正常回复的，但是在chatollama中如果使用同样的第三方代理服务，则不会回复，向量模型也无法正常使用，我的API 端口：https://sapi.onechat.fun  API Key: o9GDb5MTrDHDBVNNF9B26dA38c484560B028F4C3E5Da9fE5
希望能帮助解决，主要是想通过第三方服务使用向量模型处理大文件，因为普通官方API Key的Rate limit较小，处理大文件比较麻烦。付费key也比较难获得。感谢。

**Comment by satrong** [comment]
@carwlyjoe API 地址需要配置 https://sapi.onechat.fun/v1 才能使用

**Comment by ChaRoSaMa** [comment]
好哥们，我试了下你这api没关啊

**Comment by sugarforever** [comment]
@carwlyjoe 请勿在公开领域分享API Key，太危险了。

**Comment by sugarforever** [comment]
我更新了issue，把API key删掉了。

**Comment by Xibeirain** [comment]
你的问题解决了吗？我遇到了和你一样的问题
