### ISSUE TITLE
centos 无法访问模型

### ISSUE THREAD

**Issue by jingnorth** [sugarforever/chat-ollama#438]
后台报错，无法连接到ollama
chatollama-1  | ChatOllama is unable to establish a connection with http://host.docker.internal:11434, please check:
chatollama-1  |   1. Is Ollama server running ? (run `ollama serve` in terminal to start the server)
chatollama-1  |   2. Can the server where ChatOllama is located connect to `http://host.docker.internal:11434` ?
      chatollama-1  | Invalid token from Authorization header.

确认ollama 已经运行 
[root@wae llm]#     lsof -i :11434
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
ollama  25994 root    3u  IPv4 321000      0t0  TCP localhost:11434 (LISTEN)

docker exec -it llm-chatollama-1 bash进入容器，安装curl,提示无法解析host.docker.internal
root@7d58c58d9972:/app# curl http://host.docker.internal:11434
curl: (6) Could not resolve host: host.docker.internal

网上搜索说linux容器不支持host.docker.internal:，尝试换成主机真是ip:11434不行（可能是安全原因被禁），127.0.0.1:11434也不行，请问应该如何设置

**Comment by tanzhixu** [comment]
ollama用0.0.0.0:11434启动，页面配置为http://ip:11434

**Comment by jingnorth** [comment]
请问ollama用0.0.0.0:11434启动在哪里设置，linux下

**Comment by jingnorth** [comment]
确实2楼是正解，加了临时环境变量export OLLAMA_HOST=0.0.0.0，修改页面配置为http://ip:11434/，可以连接模型库了

**Comment by satrong** [comment]
问题看样子已解决了，issue 我就关了
