### ISSUE TITLE
在与ai对话时切换对话栏导致ai回复不显示或断字问题

### ISSUE THREAD

**Issue by dsxksss** [sugarforever/chat-ollama#439]
我觉得这应该不属于模型问题，而是chat-ollama的问题🤔，有没有什么好的解决方法呢?
![企业微信截图_17153277463234](https://github.com/sugarforever/chat-ollama/assets/73477803/7e3af4ed-ede1-4996-9245-5f4e3d5f89b2)
![企业微信截图_17153279171242](https://github.com/sugarforever/chat-ollama/assets/73477803/723b3fa7-d895-43f2-8fb1-cb2d34828d05)

**Comment by satrong** [comment]
方便提供一下 浏览器控制台 里面的日志信息吗？

**Comment by dsxksss** [comment]
> 方便提供一下 浏览器控制台 里面的日志信息吗？

![image](https://github.com/sugarforever/chat-ollama/assets/73477803/9655141c-c275-4ab5-be5d-2464c51af770)
![image](https://github.com/sugarforever/chat-ollama/assets/73477803/0dce7a13-f7f9-44f1-9090-d6ec083ecbd6)

**Comment by satrong** [comment]
你是不是在模型回复内容时切换到了另外一个对话？

**Comment by dsxksss** [comment]
> 你是不是在模型回复内容时切换到了另外一个对话？

是的，按理来说在模型回复时，我切换会话也应当不影响其他的会话内容的对吧🤔

**Comment by satrong** [comment]
目前暂时不支持在回复中切换到另外的会话

**Comment by dsxksss** [comment]
> 目前暂时不支持在回复中切换到另外的会话

好的，原来是这样，这个有在readme中说明吗?, 我没有仔细查看README, 还有就是后续会考虑该功能作为一个feat，还是说修复这个bug?

**Comment by satrong** [comment]
目前还没有时间处理这个问题，你有兴趣的话可以一起来参与

**Comment by dsxksss** [comment]
> 目前还没有时间处理这个问题，你有兴趣的话可以一起来参与

好的，因为我web前端这块技术不太好，如果有机会我我后续尝试尝试看看，感谢您的回答😀

**Comment by satrong** [comment]
该 issue 先关闭了，请关注后续

**Comment by dsxksss** [comment]
好的
