### ISSUE TITLE
chat 功能正常，知识库报错

### ISSUE THREAD

**Issue by kaikanertan** [sugarforever/chat-ollama#44]
chat 功能正常。

知识库报错如下：

> Error: Failed to batch create run: 401 Unauthorized {"detail":"Need authorization header or api key"}

**Comment by abrahammg** [comment]
Any solution to this issue?

**Comment by sugarforever** [comment]
This is very likely that you don't have the LANGSMITH_API_KEY set in the `.env`.

Please refer to `.env.example` - https://github.com/sugarforever/chat-ollama/blob/main/.env.example

```
DISABLE_VERCEL_ANALYTICS=false
OPENAI_API_KEY=
DATABASE_URL=file:../../chatollama.sqlite
CHROMADB_URL=http://localhost:8000

LANGCHAIN_TRACING_V2=true
LANGCHAIN_API_KEY=
LANGCHAIN_PROJECT=chat-ollama
```

If you make a copy of `.env` from the example, the `LANGCHAIN_TRACING_V2` is set to `true` by default while the API key is set to empty.

We included `langsmith` package in the bundle, so you will see the error above. Make sure you set `LANGCHAIN_TRACING_V2` to false if you have no langsmith API key set.

I will update the example with LANGCHAIN_TRACING_V2 set to `false` by default.

**Comment by kaikanertan** [comment]
> This is very likely that you don't have the LANGSMITH_API_KEY set in the `.env`.
> 
> Please refer to `.env.example` - https://github.com/sugarforever/chat-ollama/blob/main/.env.example
> 
> ```
> DISABLE_VERCEL_ANALYTICS=false
> OPENAI_API_KEY=
> DATABASE_URL=file:../../chatollama.sqlite
> CHROMADB_URL=http://localhost:8000
> 
> LANGCHAIN_TRACING_V2=true
> LANGCHAIN_API_KEY=
> LANGCHAIN_PROJECT=chat-ollama
> ```
> 
> If you make a copy of `.env` from the example, the `LANGCHAIN_TRACING_V2` is set to `true` by default while the API key is set to empty.
> 
> We included `langsmith` package in the bundle, and ChatOllama knowledge base is using LangChain, so when you chat with knowledge base, it will be trying to chat with LangSmith. As there's no API key set, you saw the error above. Make sure you set `LANGCHAIN_TRACING_V2` to false if you have no langsmith API key set.
> 
> I will update the example with LANGCHAIN_TRACING_V2 set to `false` by default.

重新拉取了docker image。在使用知识库时会报错另外一个404的错误：

chatollama-1  | Ollama:  {
chatollama-1  |   host: 'http://host.docker.internal:11434',
chatollama-1  |   username: 'null',
chatollama-1  |   password: 'null'
chatollama-1  | }
chatollama-1  | warn(prisma-client) This is the 10th instance of Prisma Client being started. Make sure this is intentional.
chatollama-1  | Created knowledge base RC oscillator: [object Object]
chromadb-1    | INFO:     [13-03-2024 08:07:18] 172.23.0.2:44608 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
** chatollama-1  | [nuxt] [request error] [unhandled] [500] Request to Ollama server failed: 404 Not Found**
chatollama-1  |   at OllamaEmbeddings._request (./.output/server/node_modules/@langchain/community/dist/embeddings/ollama.js:121:19)

**Comment by kaikanertan** [comment]
> 创建知识库使用的什么文本嵌入模型？确保输入框中输入的模型名前后没有空格。我记得这里目前还没有做处理。

nomic-embed-text
前后无空格。

**Comment by kaikanertan** [comment]
低级问题，没有安装“nomic-embed-text”
