### ISSUE TITLE
linux下，通过chart-ollama下载的模型放在哪个目录？

### ISSUE THREAD

**Issue by jingnorth** [sugarforever/chat-ollama#440]
下了个70b,约40G，把根分区快撑爆了，查了网上ollama放模型的位置 /usr/share/ollama/.ollama/models，并没有发现模型，我的docker不在根分区，请问chart-ollama下载的模型放在哪个目录，如何设置模型的保存位置？

**Comment by jingnorth** [comment]
好像找到了centos放在了/usr/share/ollama/.ollama/models/blobs

**Comment by satrong** [comment]
模型存放的地方取决于 Ollama ，chat-ollama 只是调用了 ollama 提供的 api 接口。如果还是没有找到存储位置，可以去 Ollama 的相关文档查找
