### ISSUE TITLE
控制台输出报错

### ISSUE THREAD

**Issue by tanzhixu** [sugarforever/chat-ollama#444]
<img width="1607" alt="截屏2024-05-12 上午11 19 42" src="https://github.com/sugarforever/chat-ollama/assets/6026899/df7a5e9f-7c3b-4cbe-b277-a7e6e3a84d23">

**Comment by satrong** [comment]
这个很奇怪，在输出关联文档的时候响应的数据不够完整导致报错。

你重新提问还会出现这种情况吗？

**Comment by tanzhixu** [comment]
我这测试有很大概率会遇到这个问题，在network的chat接口里，看到的返回数据最后一行是完整的json数据，但是在控制台中看到的就是这样的错误，我感觉还是解析json时遇到了问题。

**Comment by satrong** [comment]
如果能重现，能否再提供一下network和console里面的截图给我看看吗？

**Comment by tanzhixu** [comment]
问题：提及质量保证涉及哪些测试工件
CHAT接口返回数据：
{
	"type": "relevant_documents",
	"relevant_documents": [{
		"pageContent": "中，低），并根据优先级将这些bug按顺序修复。通过这样做，我们可以节省大量时间。\n22、解释bug的生命周期。\nbug生命周期也称为缺陷生命周期。在软件开发过程中，bug具有生命周期。该bug应该贯\n穿生命周期才能被关闭。bug的生命周期取决于所使用的工具（QC，JIRA等）以及组织中遵\n循的流程。\n建议阅读《JIRA缺陷管理工作流》\n23、什么是MR和ER？\nMR：MR代表修改请求。它用于更改软件中的现有功能，通常是客户要求的。\nER：ER代表增强报告。它用于在软件中添加新功能，通常是由客户要求的。\n24、提及某些类型的软件测试？\n建议阅读《小酋测试：测试类别知多少？》\n25、什么是CRUD测试？\nCRUD（创建，读取，更新和删除）是用于黑盒测试的一个术语。CRUD测试也是数据库测试\n的另一个术语。\nC–创建–创建新交易\nR–读取/检索–搜索或查看交易\nU–更新–编辑或修改现有事务。\nD–删除–从数据库中删除事务\n26、什么是Cookie测试？\nCookie也称为HTTPcookie，Webcookie，Internetcookie，浏览器cookie。\n建议阅读《测试之Cookie和Session知识扫盲》\n27、什么是跨浏览器测试？\n跨浏览器测试是一种非功能测试，可以帮助我们确保我们的网站或Web应用程序在各种\nWeb浏览器中都能正常运行。我们可以手动和自动方式在不同的浏览器上进行跨浏览器测\n试。要手动进行跨浏览器测试，我们（软件测试人员）会为每个浏览器创建测试，然后在每\n个浏览器上手动执行测试。为此，我们可以使用多个条件语句创建Selenium测试，这些条\n件语句根据指定的浏览器类型执行测试用例。每个浏览器都以自己的样式显示网站。通常，\n我们无法将所有浏览器都安装在一台计算机上。每个浏览器都是由不同的供应商设计的。因\n此，每个浏览器都有自己的功能来展示其独特的外观。在测试网站时，我们需要确保我们的\n网站在所有浏览器中都显示相同。为此，我们需要所有的浏览器。幸运的是，有一些工具可\n以执行跨浏览器测试，而无需手动进行单独测试。\n28、兼容性测试和跨浏览器测试有什么区别？\n兼容性测试：在不同的硬件或软件平台上测试应用程序是兼容性测试。\n示例：不同的设备（例如iPhone，三星等），不同的操作系统（例如Windows，Linux等）。\n跨浏览器测试：在不同的浏览器上测试Web应用程序是跨浏览器测试。跨浏览器测试是兼\n容性测试的子集。\n例如：谷歌浏览器，IE10，IE11，Firefox43等。\n29、什么是配置管理？\n配置管理是在项目生命周期中用来控制和记录每一个更改的过程。\n30、您在测试过程中使用了哪些工具？\n我在测试过程中使用的工具如下：\n测试管理工具：JIRA，TestLodge，QualityCenter\n测试用例管理工具：TestCaseLab\n缺陷跟踪工具：Bugzilla，MantisBT",
		"metadata": {
			"blobType": "application/pdf",
			"source": "qa.pdf"
		}
	}, {
		"pageContent": "自动化工具：QTP/UFT，Selenium，LoadRunner、Pytest\nGUI测试工具：FroglogicSquish\n跨浏览器测试工具：CrossBrowserTesting，BrowserStack",
		"metadata": {
			"blobType": "application/pdf",
			"source": "qa.pdf"
		}
	}, {
		"pageContent": "1、质量保证（QA）和质量控制（QC）有什么区别？\n质量保证：质量保证涉及面向过程的活动。它确保了防止在进行软件应用程序过程中出现缺\n陷。因此，在开发软件应用程序时不会出现缺陷。\n质量控制：质量控制涉及以产品为导向的活动。它执行程序或代码以识别软件应用程序中的\n缺陷。\n2、预防和反应方法在测试中有什么区别？\n预防方法：也称为验证过程。这种方法是为了防止缺陷。在这种方法中，测试是在SDLC的\n早期阶段设计的，即在软件生产之前。在这种方法中，测试人员尝试在早期阶段预防缺陷，\n它属于质量分析。\n反应性方法：也称为验证过程。这种方法是识别缺陷。通过这种方法，测试被设计为在软件\n生产完成后执行。在这里，我们尝试查找缺陷。它受到质量控制。\n3、您为什么要进行质量QA？\n我参加质量QA是因为我喜欢这份工作。\n4、列出QA工程师的角色？\n软件质量保证工程师通常涉及以下任务：\n质量检查小组负责监控整个开发过程。\n他们负责跟踪SDLC每个阶段的结果并进行调整以满足期望。\n他们负责阅读和理解需求文档。\n分析测试需求，设计和执行测试。\n开发测试用例并确定测试活动的优先级。\n根据项目的问题和问题管理计划记录问题。\n与应用程序团队和/或客户一起解决在测试过程中出现的任何问题。\n每次对代码进行更改以修复缺陷时，都要进行回归测试。\n必须与客户互动以更好地了解产品要求。\n参加测试过程的演练。\n5、解释QA测试的过程？\n简而言之，QA测试过程是一个逐步的过程，涉及分析需求文档，准备测试策略，测试计划\n和测试用例，在构建就绪时执行测试用例。在执行过程中，QA人员执行不同类型的测试，\n以确保软件达到或超过预期。\n6、文档在质量保证中的作用是什么？\n文档在质量保证中起着至关重要的作用。SDLC中涉及的所有文档，例如业务需求规范，设\n计，检查报告，配置，代码更改，测试策略，测试计划，测试用例，错误报告，用户手册，\n都应记录在案。\n文档帮助我们获得高质量的软件产品；\n有必要使用文档来使事情变得更真实；\n我们可以将文档用作参考资料，并在必要时重新使用；\n通过维护适当的文档，我们可以节省组织的大量时间，精力和金钱；\n正确的文档可以使客户轻松查看软件过程。\n7、什么是质量审核？\n质量审核是对软件产品或过程进行系统和独立检查以评估是否符合规格，标准，协议和其他\n相关标准的过程。\n8、提及质量保证涉及哪些测试工件？\n质量保证涉及的测试工件包括测试策略，测试计划，测试方案，测试用例，测试摘要报告，\nbug报告等。",
		"metadata": {
			"blobType": "application/pdf",
			"source": "qa.pdf"
		}
	}, {
		"pageContent": "bug报告又名缺陷报告，它向开发人员传达有关bug的详细信息（例如环境详细信息，重现\n步骤等）。它使开发人员可以轻松地复现该错误。bug报告的关键组成部分包括缺陷ID，缺\n陷标题，报告者名称，缺陷报告日期，报告者指定，项目名称，发行版本，环境详细信息，\n缺陷优先级，缺陷严重性，缺陷状态，缺陷描述，重现该bug的步骤，预期结果，实际结果，\n附件（如有）和缺陷截止日期。\n17、告诉我一些在编写bug报告时要考虑的关键点。\n①重现该bug2-3次。\n②使用一些与您的bug相关的关键字，然后在“缺陷跟踪工具”中进行搜索。\n③检查类似的模块。\n④立即报告问题。\n⑤编写详细的步骤来重现该bug。\n⑥写一个好的缺陷总结。在编写bug报告的过程中请注意您的描述，您的文字不应该冒犯他\n人。\n⑦建议使用适当的屏幕截图来说明问题。\n⑧在发布bug报告之前，先对bug报告进行两次或三次校对。\n18、自动化测试的优点和缺点是什么？\n优点：\n自动化测试执行速度更快；\n从长远来看，与手动测试相比更便宜；\n自动化测试更可靠；\n自动化测试功能更强大，用途更广；\n它主要用于回归测试；\n它不需要人工干预，测试脚本可以无人值守运行；\n它有助于增加测试范围；\n缺点：\n仅推荐用于稳定的产品；\n自动化测试最初很昂贵；\n大多数自动化工具都很昂贵；\n它有一些限制，例如处理验证码、字体、颜色；\n需求反复变化时需要大量维护；\n并非所有工具都支持各种测试，例如Windows，Web，移动性，性能/负载测试。\n19、构建和发布之间有什么区别？\n构建：构建是软件的版本。每个版本都有一个用于标识的编号。Build是发行版的预发行版\n本。开发人员将构建权交给测试团队，以在本地测试应用程序。内部版本号是递增的。\n发布：发布是软件开发团队将应用程序最终版本分发给客户的过程。\n20、什么是bug泄漏和bugrelease？\nbug泄漏：测试团队在测试过程中实际上遗漏的bug，并将构建版本发布到生产环境中。如\n果现在最终用户或客户发现了该bug（测试团队遗漏了该bug），则我们将其称为bug泄漏。\nbugrelease：将带有某些已知bug的软件发布到生产环境中，然后我们将其称为bugrelease。\n这些已知的bug应包含在发行说明中。在其他情况下，将软件与严重程度和优先级较低的一\n些已知bug发布给测试团队。在发布到生产环境之前，可以移除这些bug。\n21、什么是Bug分类？\nbug分类是一个正式的过程，可以根据bug的严重性，发生频率，风险和其他重要参数来确\n定优先级，从而找出重要的bug。测试人员在bug分类会议中为每个bug分配优先级（高，",
		"metadata": {
			"blobType": "application/pdf",
			"source": "qa.pdf"
		}
	}]
}
![console](https://github.com/sugarforever/chat-ollama/assets/6026899/14503334-fd0d-4370-8978-fe734292c777)
![json_echo](https://github.com/sugarforever/chat-ollama/assets/6026899/93f905c1-e3f4-4be5-b7d0-041c27fefaac)
![network](https://github.com/sugarforever/chat-ollama/assets/6026899/8bf8624b-b7dd-4079-a0c8-4c375b9c5bc5)

**Comment by satrong** [comment]
感谢，我能重现了，我找找什么原因导致的

**Comment by satrong** [comment]
@tanzhixu 已修复，请获取最新代码再试试

**Comment by satrong** [comment]
@tanzhixu  我猜你提的另外一个问题 #423 跟这个问题是同一个原因

**Comment by tanzhixu** [comment]
> @tanzhixu 我猜你提的另外一个问题 #423 跟这个问题是同一个原因

是的，从现象看是同一个问题

**Comment by tanzhixu** [comment]
> @tanzhixu 已修复，请获取最新代码再试试

偶尔还会有这个问题

**Comment by satrong** [comment]
下次再遇到，请再提供一些信息给我看看，感谢
