### ISSUE TITLE
500报错以及没有模型无法实现

### ISSUE THREAD

**Issue by swdnn18** [sugarforever/chat-ollama#45]
![1710234462386](https://github.com/sugarforever/chat-ollama/assets/163115433/a17e0fd6-57b1-4064-9961-b5934c38f7b9)
![1710234488113](https://github.com/sugarforever/chat-ollama/assets/163115433/bfdd7b35-63f0-422a-95a2-3e991b30eced)
还经常报错一些没见过的错误  步骤也是按照文档来的  尝试两边 只是可以跑起来但是没办法沟通

**Comment by satrong** [comment]
似乎你没有设置 ollama 的地址：
![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/27588b51-7b3d-4417-a431-80eb68ba1650)

**Comment by sugarforever** [comment]
补充一下，如果是运行的开发服务器，Ollama服务器设置为http://127.0.0.1:11434。如果是docker容器，要访问本地Ollama，需要设置服务器为http://host.docker.internal:11434

Docker运行ChatOllama请参考：
https://github.com/sugarforever/chat-ollama?tab=readme-ov-file#users-guide

**Comment by swdnn18** [comment]
我用的是Docker运行的ChatOllama  配置地址后model500报错
![image](https://github.com/sugarforever/chat-ollama/assets/163115433/13086b92-6622-44a7-b140-c0ea8b761f07)
![image](https://github.com/sugarforever/chat-ollama/assets/163115433/34f993ab-a609-4bbb-b617-8347302eec80)
![image](https://github.com/sugarforever/chat-ollama/assets/163115433/4c683a28-f5e3-40b9-a483-2d8914906cc4)
![image](https://github.com/sugarforever/chat-ollama/assets/163115433/e7f597c2-e359-467a-b095-2c99dbf72d63)

**Comment by sugarforever** [comment]
Invalid URL，应该是没有正确配置Ollama的地址吧。分享下你在Settings里设置的Ollama Server

**Comment by swdnn18** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/163115433/f808b9fa-dad4-43e2-8c72-c793a583f401)
![image](https://github.com/sugarforever/chat-ollama/assets/163115433/ffa67dac-6bb5-4bac-bbfc-f33c1ca4aeb5)

Ollama服务器地址是可以访问的通

**Comment by swdnn18** [comment]
已经不报错了  我运行的开发服务器  开发服务器内是没有model的吗  是需要自己添加数据库和model的吗

**Comment by satrong** [comment]
可以在 https://ollama.com/library 这里找可以安装的模型，比如要按照 `gemma` 这个模型，可以在 chat-ollama 网页中的 Models 页面下载
![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/7c457fa9-4891-4c49-84b7-f3c6cd7b9af1)


建议去看看作者的B站的视频

**Comment by swdnn18** [comment]
![image](https://github.com/sugarforever/chat-ollama/assets/163115433/15277c10-6609-41be-b5b9-32991f76a698)
为什么会出现这个错误 之前也出现过 不过刷新几下就好了

**Comment by sugarforever** [comment]
> ![image](https://private-user-images.githubusercontent.com/163115433/312339912-15277c10-6609-41be-b5b9-32991f76a698.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTg0NDksIm5iZiI6MTcxMDMxODE0OSwicGF0aCI6Ii8xNjMxMTU0MzMvMzEyMzM5OTEyLTE1Mjc3YzEwLTY2MDktNDFiZS1iNWI5LTMyOTkxZjc2YTY5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwODIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODZlMTVjOGNlY2YzMWFkNWIzMTE0NTk0ZmQwYmZjZWRmM2YxNmZkZjQzNDBkMzNiZTVmMzdjZDdlNDlmZGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OTPPCOGaT9lRhxT6e51rrmQWtsU0yYPs3wfIJcHPm_M) 为什么会出现这个错误 之前也出现过 不过刷新几下就好了

这个错误暂时没有看出来是哪里的问题

**Comment by sugarforever** [comment]
> ![image](https://private-user-images.githubusercontent.com/163115433/312340561-114852cf-28c5-4a88-a130-f9c79aaefe47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTg0NDksIm5iZiI6MTcxMDMxODE0OSwicGF0aCI6Ii8xNjMxMTU0MzMvMzEyMzQwNTYxLTExNDg1MmNmLTI4YzUtNGE4OC1hMTMwLWY5Yzc5YWFlZmU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwODIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTc2YjZmNzc2ZjQ3ZjIwYzNlYWM5YmExYjk1ZDMxYjRjYmNkZDg4ZWM4Yzg0ZTUwNzk0YWZkZGM5YmRhNjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g10R36peXaM09RcnYCRro9jfrNZ_-f314K6FjRdVXkc)



> ![image](https://private-user-images.githubusercontent.com/163115433/312340561-114852cf-28c5-4a88-a130-f9c79aaefe47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTg0NDksIm5iZiI6MTcxMDMxODE0OSwicGF0aCI6Ii8xNjMxMTU0MzMvMzEyMzQwNTYxLTExNDg1MmNmLTI4YzUtNGE4OC1hMTMwLWY5Yzc5YWFlZmU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwODIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTc2YjZmNzc2ZjQ3ZjIwYzNlYWM5YmExYjk1ZDMxYjRjYmNkZDg4ZWM4Yzg0ZTUwNzk0YWZkZGM5YmRhNjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g10R36peXaM09RcnYCRro9jfrNZ_-f314K6FjRdVXkc)

这是因为localStorage只能在客户端才有效。ModelsDropDown.vue里最新代码应该已经做了处理，组件会运行在客户端。你运行的是什么版本的代码？

**Comment by satrong** [comment]
@sugarforever  我觉得可以做前后端分离，现在项目有点绕😂

如果搞分离，前端部分我可以来弄，后端如果用 nodejs 我也可以参与

**Comment by sugarforever** [comment]
> @sugarforever 我觉得可以做前后端分离，现在项目有点绕😂
> 
> 如果搞分离，前端部分我可以来弄，后端如果用 nodejs 我也可以参与

短期我们先按这个架构来，大家也借此机会熟悉一下Nuxt 3。

**Comment by meokey** [comment]
@sugarforever  作为容器在后端运行后，在哪儿可以看到 logs 啊？
我也是500报错，找不到模型。但是同样的Ollama设置，Ollama Open WebUI是可以找到模型的。而且我设置了Anthropic的API后，也是找不到Chaulde的模型。我没有设置OPENAI的API，与这有没有关系？
我是Ollama, Chroma和ChatOllama分别运行在同一台机器上的独立的容器中的，用172.xxx.xx.xxx的地址互联。

**Comment by swdnn18** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/163115433/312340561-114852cf-28c5-4a88-a130-f9c79aaefe47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTg0NDksIm5iZiI6MTcxMDMxODE0OSwicGF0aCI6Ii8xNjMxMTU0MzMvMzEyMzQwNTYxLTExNDg1MmNmLTI4YzUtNGE4OC1hMTMwLWY5Yzc5YWFlZmU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwODIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTc2YjZmNzc2ZjQ3ZjIwYzNlYWM5YmExYjk1ZDMxYjRjYmNkZDg4ZWM4Yzg0ZTUwNzk0YWZkZGM5YmRhNjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g10R36peXaM09RcnYCRro9jfrNZ_-f314K6FjRdVXkc)
> 
> > ![图像](https://private-user-images.githubusercontent.com/163115433/312340561-114852cf-28c5-4a88-a130-f9c79aaefe47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTg0NDksIm5iZiI6MTcxMDMxODE0OSwicGF0aCI6Ii8xNjMxMTU0MzMvMzEyMzQwNTYxLTExNDg1MmNmLTI4YzUtNGE4OC1hMTMwLWY5Yzc5YWFlZmU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwODIyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTc2YjZmNzc2ZjQ3ZjIwYzNlYWM5YmExYjk1ZDMxYjRjYmNkZDg4ZWM4Yzg0ZTUwNzk0YWZkZGM5YmRhNjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g10R36peXaM09RcnYCRro9jfrNZ_-f314K6FjRdVXkc)
> 
> 这是因为localStorage只能在客户端才有效。ModelsDropDown.vue里最新代码应该已经做了处理，组件会在客户端运行。你运行的是哪个版本的代码？

我运行的最新版本的代码  还是回报localStorage的错误 还有页面中node的问题

**Comment by satrong** [comment]
@swdnn18 根据 localStorage 的这个错误，我能想到的就是代码不是最新的😂

用 `git log` 查看下你本地代码最新的是哪条记录

**Comment by satrong** [comment]
@swdnn18  我本地也出现这个问题了，可能是代码问题

**Comment by satrong** [comment]
https://github.com/sugarforever/chat-ollama/blob/bf62aee4d874a2f8e027b273943723107d91dc57/utils/settings.ts#L19C38-L22

@sugarforever 问题还是在这个函数，因为组件在服务端渲染时调用了这个方法导致报错的。这个问题影响还挺大的，我这个PR进行了重构 #58
