### ISSUE TITLE
创建本地知识库报错

### ISSUE THREAD

**Issue by ethansun1986** [sugarforever/chat-ollama#451]
知识库报错：Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.htm

上传的文件是doc文档

**Comment by satrong** [comment]
印象中是不支持 doc 格式，你可以将 doc 转换成 docx ，或者转换成 pdf

**Comment by ethansun1986** [comment]
谢谢

左禾右惠 ***@***.***> 于2024年5月28日周二 21:08写道：
