### ISSUE TITLE
[FR]增加对话清除

### ISSUE THREAD

**Issue by jingnorth** [sugarforever/chat-ollama#455]
UI上没有找到对话清除方式，想要全新的对话，不受之前对话的影响，目前只能新建一个对话

**Comment by sugarforever** [comment]
你是期望清除对话中的部分消息吗？

**Comment by satrong** [comment]
如果我没猜错的话应该是清空当前会话的所有消息，正好我也有做这个功能的打算

**Comment by jingnorth** [comment]
是的，清除当前对话的所有消息，目的是不受之前累积会话的影响。另外问下，docker安装的是否有版本更新的办法，目前仿佛无法用到你们修改过的版本吧

**Comment by satrong** [comment]
应该是直接拉最新镜像吧

**Comment by satrong** [comment]
已支持

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/4b51b69f-c456-4865-95c3-28ca9944411f)
