### ISSUE TITLE
在Models Tab 下载nomic-embed-text出错

### ISSUE THREAD

**Issue by zhangningboo** [sugarforever/chat-ollama#46]
代码版本Git Commit ID: 2dd0ddd69f6751944ade955b994f2564d08feeac 
点击下载，后台报错，
![图片](https://github.com/sugarforever/chat-ollama/assets/110680007/b510197f-29ff-40a1-aca3-af51ce5a8ce3)

错误信息：
```shell
Ollama:  { host: 'null', username: 'null', password: 'null' }
Authorization: dW5kZWZpbmVkOnVuZGVmaW5lZA==
[nuxt] [request error] [unhandled] [500] fetch failed
  at node:internal/deps/undici/undici:12345:11  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Ollama:  { host: 'null', username: 'null', password: 'null' }
Authorization: dW5kZWZpbmVkOnVuZGVmaW5lZA==
[nuxt] [request error] [unhandled] [500] fetch failed
  at node:internal/deps/undici/undici:12345:11  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Ollama:  { host: 'null', username: 'null', password: 'null' }
Authorization: dW5kZWZpbmVkOnVuZGVmaW5lZA==
[nuxt] [request error] [unhandled] [500] fetch failed
  at node:internal/deps/undici/undici:12345:11  
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

![图片](https://github.com/sugarforever/chat-ollama/assets/110680007/5660587f-c6f4-445d-a771-15afbc604bb0)

**Comment by sugarforever** [comment]
请确认你使用的node版本，最近有不少用户报了类似问题。升级node到 `v20.5.1` 或以上，应该能解决这个问题。

如果还有问题的话，尝试重启Ollama。

**Comment by zhangningboo** [comment]
使用的版本是`v20.11.1`
```shell
$ node --version               
v20.11.1
```
![图片](https://github.com/sugarforever/chat-ollama/assets/110680007/035e60f3-3f20-46a5-98ae-53065ab5da41)

**Comment by zhangningboo** [comment]
请问ollama的版本有要求吗？我理解是chat-ollama是调用ollma的api，ollama的api是否会变动？

**Comment by wgong** [comment]
@zhangningboo I got the same error while running docker version, but no issue after switching to cloned version locally (I have to upgrade ollama to v0.1.29 to fix issue with using `nomic-embed-text`

**Comment by zhangningboo** [comment]
I updated the ollama version to `v0.1.29`， it doesn't work.
<img src="https://github.com/sugarforever/chat-ollama/assets/110680007/c67322da-8f45-4896-9a43-713c99411ca5 " width="60%">

<img src="https://github.com/sugarforever/chat-ollama/assets/110680007/70533ae1-0739-44e3-835e-7152238ea213 " width="60%">
