### ISSUE TITLE
Embedding模型在ollama中拉取的bge-large-zh-v1.5为什么在chatollama的embedding模型中选不了这个模型，识别不到，可选的只有nomic-text

### ISSUE THREAD

**Issue by iaoxuesheng** [sugarforever/chat-ollama#464]
Embedding模型在ollama中拉取的bge-large-zh-v1.5为什么在chatollama的embedding模型中选不了这个模型，识别不到，可选的只有nomic-text

**Comment by chen865** [comment]
这个需要你自己手动输入从ollama拉取的模型，这个作者之前有提到过，暂时还没有联动。你可以直接在模型那个地方输入你拉取的模型名称，比如你这个就输入：“bge-large-zh-v1.5”。你可以重新尝试一下

**Comment by satrong** [comment]
> 这个需要你自己手动输入从ollama拉取的模型，这个作者之前有提到过，暂时还没有联动。你可以直接在模型那个地方输入你拉取的模型名称，比如你这个就输入：“bge-large-zh-v1.5”。你可以重新尝试一下

是的。因为Ollama目前没有提供用于区分文本嵌入模型的方法，能看到 nomic-text 是因为代码中做了特殊的处理

**Comment by tankGe** [comment]
是不是意味着嵌入模型Ollama中只能用列出的nomic-embed-text:latest，其他下载的都不能用？

**Comment by satrong** [comment]
可自定义输入，前提是你已安装输入的文本嵌入模型
