### ISSUE TITLE
[FR] 回答显示模型名字

### ISSUE THREAD

**Issue by wwjCMP** [sugarforever/chat-ollama#467]
由于有很多模型可选，在回答的最后显示模型的文字（和耗时），方便对比不同模型的回答质量。
不作为上下文的一部分，只作为额外显示的信息。

**Comment by satrong** [comment]
预计 [#469](https://github.com/sugarforever/chat-ollama/issues/469) 中会增加该功能

**Comment by satrong** [comment]
已完成
