### ISSUE TITLE
【功能建议】风险：建议增加管理员账户，现在注册的每一个账户进去都能删除模型，看到key，太可怕了

### ISSUE THREAD

**Issue by ddup001** [sugarforever/chat-ollama#475]
如题，建议增加管理员账户，现在注册的每一个账户进去都能删除模型，看到key，太可怕了

**Comment by ddup001** [comment]
模型与设置只对管理员账户开放，其它对普通用户开放

**Comment by sugarforever** [comment]
目前ChatOllama的设计原则是：
1. API key等配置信息都是客户端存储，存储在浏览器的本地存储中。
2. 服务端不存储任何Key等信息。
3. 注册用户与角色暂时与密钥管理无关。

也就是说，你所登录账号与密钥是无关的。你的账号配置的密钥与Ollama设置仅在同一浏览器中可见。

关于用户角色，账号管理，密钥管理，模型管理，短期内不会做大的改动。请在将这个项目部署到服务器供多人使用前，确保理解应用的数据管理方式。

**Comment by satrong** [comment]
密钥 那些数据都是存储在浏览器端的，只有请求 API 时才会将密钥这些数据传递给服务端使用，但服务端不会存储。为了密钥安全建议个人部署使用
