### ISSUE TITLE
[BUG] 更新之后不支持ollama中其他用户上传的模型

### ISSUE THREAD

**Issue by wwjCMP** [sugarforever/chat-ollama#504]
用户名/模型

![image](https://github.com/sugarforever/chat-ollama/assets/32979859/c8f97977-a7ca-444a-a881-6b1984620e8e)

**Comment by satrong** [comment]
模型全名叫什么？

**Comment by wwjCMP** [comment]
所有的都不行，就是模型名为  用户名/模型形式  的都不行。只显示用户名

**Comment by satrong** [comment]
已修复

**Comment by sugarforever** [comment]
@satrong @wwjCMP 是否能分享几个带有 / 的模型名？

**Comment by sugarforever** [comment]
> @satrong @wwjCMP 是否能分享几个带有 / 的模型名？

嗯。我看到了 https://ollama.com/vanilj/smaug-llama-3-70b-instruct
