### ISSUE TITLE
[bug]使用ollama的嵌入模型导入pdf的时候经常会失败

### ISSUE THREAD

**Issue by wwjCMP** [sugarforever/chat-ollama#505]
不是不能导入，但是经常会失败，要重复进行嵌入才能成功。

**Comment by satrong** [comment]
方便提供失败的错误信息吗？

**Comment by heimy2000** [comment]
> 不是不能导入，但是经常会失败，要重复进行嵌入才能成功。

请检查chromadb或8000端口是否有占用问题

**Comment by wwjCMP** [comment]
> > 不是不能导入，但是经常会失败，要重复进行嵌入才能成功。
> 
> 请检查chromadb或8000端口是否有占用问题

更新了ollama和chat-ollama之后现在没有这问题了
