### ISSUE TITLE
无法连接已安装ollama，获取models

### ISSUE THREAD

**Issue by wuqrmm** [sugarforever/chat-ollama#52]
你好，按照教程用docker已经在服务器部署了chatollama，服务器也安装了ollama服务，下载了几个模型。也可以正常运行。
tcp        0      0 127.0.0.1:11434         0.0.0.0:*               LISTEN      2216/ollama
但是按照教程设置了Ollama server to http://host.docker.internal:11434，刷新model无法显示已下载的model，后台报错[nuxt] [request error] [unhandled] [500] fetch failed
chatollama-1 | at Object.fetch (node:internal/deps/undici/undici:11576:11)
chatollama-1 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)，请指教

**Comment by sugarforever** [comment]
host.docker.internal只在Docker Desktop上有效。服务器上没有这个特性。你应该需要容器化跑一个ollama，然后把本地环境中ollama的模型目录挂载进去。你可以尝试一下。

我一会儿提交一个支持这个的docker-compose.yaml版本。

**Comment by wuqrmm** [comment]
感谢回复，期待支持的版本

**Comment by sugarforever** [comment]
> 感谢回复，期待支持的版本

测试一下 这个版本 - https://github.com/sugarforever/chat-ollama/blob/main/docker-compose-ollama.yaml

我没有Linux服务器，没法验证GPU相关的指令。

你的服务器上有GPU吗？https://docs.docker.com/config/containers/resource_constraints/#gpu
确保安装nvidia container toolkit https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by wuqrmm** [comment]
谢谢回复，我的服务器没有gpu。一直在思考，有没有办法让docker运行的chat-ollama直接访问服务器上安装的ollama服务，而不是通过docker再跑一个ollama服务。例如网络模式采用host，是不是可以实现直接访问

**Comment by wuqrmm** [comment]
另外找了半天没找到centos下ollama下载模型的默认目录，向映射下模型目录，免得重复下载。

**Comment by richwu** [comment]
我的GPU版的docker-compose-ollama.yaml 发上来做一个参考
`version: '3.1'
services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - chromadb_data:/chroma/.chroma/index

  chatollama:
    environment:
      - CHROMADB_URL=http://chromadb:8000
      - DATABASE_URL=file:/app/sqlite/chatollama.sqlite
    image: 0001coder/chatollama:latest
    ports:
      - "3000:3000"
    pull_policy: always
    restart: always
    volumes:
      - ~/.chatollama:/app/sqlite

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
volumes:
  chromadb_data:
`

**Comment by wgong** [comment]
@richwu can you share the yaml file, I failed to run chat-ollama in docker, Thanks

**Comment by DeSireFire** [comment]
> 我的GPU版的docker-compose-ollama.yaml 发上来做一个参考 <img alt="image" width="188" src="https://private-user-images.githubusercontent.com/758242/313050062-a9f8489b-f150-4bf8-acc9-175b52051b4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTI4NzMsIm5iZiI6MTcxMDc1MjU3MywicGF0aCI6Ii83NTgyNDIvMzEzMDUwMDYyLWE5Zjg0ODliLWYxNTAtNGJmOC1hY2M5LTE3NWI1MjA1MWI0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQwOTAyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjBjZTJkZGY0MDUwYjI1NDRhZTdlNjhlODk5N2Y1ZWZjMWZiYjdkOWRiNmFlNDNmNmM1NTc0OWFkMjM4MDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lhr_OBGid4B-jyTDs1NdvtdGNMLKFyaA9ckWnCb0K_U">

大佬好，可以来一份你完整的docker-compose.yaml文件吗？
敏感的地方你做个脱敏就好。谢谢orz

**Comment by Xyolan** [comment]
[host.docker.internal：](http://host.docker.internal:11434/)
你和我一样ollama server是安装在windows内，而chatollama安装在docker中，所有的教程都没有说这个
你只需要在Ollama server setting中填写：http://host.docker.internal:11434/
这是docker容器内访问本机网络的方式。

**Comment by Xyolan** [comment]
> 你好，按照教程用docker已经在服务器部署了chatollama，服务器也安装了ollama服务，下载了几个模型。也可以正常运行。 tcp 0 0 127.0.0.1:11434 0.0.0.0:* LISTEN 2216/ollama 但是按照教程设置了Ollama server to [http://host.docker.internal:11434，刷新model无法显示已下载的model，后台报错[nuxt]](http://host.docker.internal:11434%EF%BC%8C%E5%88%B7%E6%96%B0model%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E5%B7%B2%E4%B8%8B%E8%BD%BD%E7%9A%84model%EF%BC%8C%E5%90%8E%E5%8F%B0%E6%8A%A5%E9%94%99%5Bnuxt%5D) [request error] [unhandled] [500] fetch failed chatollama-1 | at Object.fetch (node:internal/deps/undici/undici:11576:11) chatollama-1 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)，请指教

你和我一样ollama server是安装在windows内，而chatollama安装在docker中，所有的教程都没有说这个
你只需要在Ollama server setting中填写：http://host.docker.internal:11434/
这是docker容器内访问本机网络的方式。

**Comment by allenpatient** [comment]
> > 你好，按照教程用docker已经在服务器部署了chatollama，服务器也安装了ollama服务，下载了几个模型。也可以正常运行。 tcp 0 0 127.0.0.1:11434 0.0.0.0:* LISTEN 2216/ollama 但是按照教程设置了Ollama server to [http://host.docker.internal:11434，刷新model无法显示已下载的model，后台报错[nuxt]](http://host.docker.internal:11434%EF%BC%8C%E5%88%B7%E6%96%B0model%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E5%B7%B2%E4%B8%8B%E8%BD%BD%E7%9A%84model%EF%BC%8C%E5%90%8E%E5%8F%B0%E6%8A%A5%E9%94%99%5Bnuxt%5D) [request error] [unhandled] [500] fetch failed chatollama-1 | at Object.fetch (node:internal/deps/undici/undici:11576:11) chatollama-1 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)，请指教
> 
> 你和我一样ollama server是安装在windows内，而chatollama安装在docker中，所有的教程都没有说这个 你只需要在Ollama server setting中填写：http://host.docker.internal:11434/ 这是docker容器内访问本机网络的方式。

设置后能看到Models下面的各个模型了。

**Comment by Tigerpop** [comment]
> 你好，按照教程用docker已经在服务器部署了chatollama，服务器也安装了ollama服务，下载了几个模型。也可以正常运行。 tcp 0 0 127.0.0.1:11434 0.0.0.0:* LISTEN 2216/ollamatcp 0 0 127.0.0.1：11434 0.0.0.0：* 收听 2216/ollama 但是按照教程设置了Ollama server to [http://host.docker.internal:11434，刷新model无法显示已下载的model，后台报错[nuxt]](http://host.docker.internal:11434%EF%BC%8C%E5%88%B7%E6%96%B0model%E6%97%A0%E6%B3%95%E6%98%BE%E7%A4%BA%E5%B7%B2%E4%B8%8B%E8%BD%BD%E7%9A%84model%EF%BC%8C%E5%90%8E%E5%8F%B0%E6%8A%A5%E9%94%99%5Bnuxt%5D) [request error] [unhandled] [500] fetch failed chatollama-1 | at Object.fetch (node:internal/deps/undici/undici:11576:11)查托拉马-1 |在 Object.fetch （node：internal/deps/undici/undici：11576：11） chatollama-1 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)，请指教查托拉马-1 |at process.processTicksAndRejections （node：internal/process/task_queues：95：5），请指教

请问你的问题有得到解决吗？ 我也遇到了和你一模一样的问题。

**Comment by y0umu** [comment]
> host.docker.internal只在Docker Desktop上有效。服务器上没有这个特性。你应该需要容器化跑一个ollama，然后把本地环境中ollama的模型目录挂载进去。你可以尝试一下。
> 
> 我一会儿提交一个支持这个的docker-compose.yaml版本。

If you are running docker on linux, you probably don't have to mess up with host.docker.internal but use docker's bridge IP directly instead (usually 172.17.0.1, check with `ip addr show docker0`). That said, fill in settings>host with `http://172.17.0.1:11434`. Note that under such circumstance your ollama instance should [bind to 0.0.0.0](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-linux) instead of `127.0.0.1`.

Also you may also need to add an additional rule to your firewall. For firewalld based systems (RHEL, fedora, CentOS, Rocky, etc), check https://unix.stackexchange.com/questions/199966/how-to-configure-centos-7-firewalld-to-allow-docker-containers-free-access-to-th.
