### ISSUE TITLE
BGE-M3嵌入模型无法在知识库中加载

### ISSUE THREAD

**Issue by xixia123** [sugarforever/chat-ollama#522]
下载了bge的嵌入模型，在创建知识库时，无法选择bge，弹出的选项只有ollam、openai和gemmi的嵌入模型，请问该如何解决。

下载的是smartcreation/bge-large-zh-v1.5:latest模型

**Comment by satrong** [comment]
没有选项时可手动输入嵌入模型名

**Comment by xixia123** [comment]
> 没有选项时可手动输入嵌入模型名

okok,试了一下，能起效果，就是好像pdf的识别效果都差不多的，不太行

**Comment by satrong** [comment]
ok
