### ISSUE TITLE
Gemini代理

### ISSUE THREAD

**Issue by xixia123** [sugarforever/chat-ollama#527]
Gemini没有代理选型可以选择
![image](https://github.com/sugarforever/chat-ollama/assets/51846887/11b9109d-2fb9-4753-8b11-9adf215f2dbd)

**Comment by satrong** [comment]
已支持，由于我无法使用 Gemini，所以未经过测试，期待你的使用和反馈

**Comment by xixia123** [comment]
> 已支持，由于我无法使用 Gemini，所以未经过测试，期待你的使用和反馈

经过测试，可以正常使用了，需要将端点设置为https://generativelanguage.googleapis.com，然后勾选代理
