### ISSUE TITLE
[BUG] 对话丢失 

### ISSUE THREAD

**Issue by wwjCMP** [sugarforever/chat-ollama#537]
可能是浏览器异常关闭导致

**Comment by satrong** [comment]
请提供详细的信息

**Comment by wwjCMP** [comment]
> 请提供详细的信息

很难具体提供，用着用着对话就丢失了。有可能是浏览器的问题，也有可能是更新chat-ollama的问题。反正是过一段时间，对话就消失不见了。

**Comment by wwjCMP** [comment]
> 丢失是全部丢失，还是部分丢失？
> 
> 有没有清理过浏览器缓存？

全部没有。没有清理过缓存

**Comment by ngaiyuc** [comment]
I have encountered this bug before. You may need to stop and restart the entire container manually in Docker Desktop. This issue can occur when you reboot your computer, as some containers may not be properly prepared.
