### ISSUE TITLE
自定义设置OpenRouter的API服务无法正常适用

### ISSUE THREAD

**Issue by xixia123** [sugarforever/chat-ollama#547]
设置
![image](https://github.com/user-attachments/assets/aeee0aef-6b82-4708-a8af-46c3210daa20)

报错
![image](https://github.com/user-attachments/assets/30f8e607-6972-4a0d-a331-815962fd839c)

**Comment by satrong** [comment]
国内访问不吧？代理好像也不行

**Comment by xixia123** [comment]
> 国内访问不吧？代理好像也不行

应该不是代理问题，openrouter不需要代理可以直接访问的

**Comment by satrong** [comment]
你把端点设置为 `https://openrouter.ai/api` 试试

**Comment by xixia123** [comment]
> 你把端点设置为 `https://openrouter.ai/api` 试试

可以使用了，感谢感谢！
