### ISSUE TITLE
[BUG] 聊天界面，发送的问题显示不完全

### ISSUE THREAD

**Issue by kinger310** [sugarforever/chat-ollama#554]
【问题】
如果发送带有类似于HTML的标签的问题，`<html>`会显示不出来。

![微信截图_20240723154512](https://github.com/user-attachments/assets/b6587a4f-a41d-48e1-8788-a296aeb4b5f0)

【解决思路】
我定位代码是`ChatMessageItem.vue `中
```
<pre v-else v-html="message.content" class="p-3 whitespace-break-spaces" />
```
我在想，是否可以参考回答框的代码，改成
```
v-html="markdown.render(message.content || '')"
```
但是改完之后样式不好看，我还不怎么会调整样式。
老师们是否可以给个指导。
![微信截图_20240723155116](https://github.com/user-attachments/assets/5f904a3a-014a-4f7b-b323-97963d3bce61)

**Comment by satrong** [comment]
要不然改成？

```html
<pre v-else v-text="message.content" class="p-3 whitespace-break-spaces" />
```
