### ISSUE TITLE
[FR] 第三方代理服务，支持非Openai模型的类Openai风格调用

### ISSUE THREAD

**Issue by kinger310** [sugarforever/chat-ollama#562]
【问题】
在使用AI超市等第三方代理服务时，如 [wildcard](https://wildcard.com.cn/api)，[302ai](https://302.ai/)。这些服务调用非openai模型，例如anthropic, gemini等模型，基本上都是类Openai风格调用。也就是调用`/chat/completions`接口。

所以在chat-ollama上，使用这种服务，会出现如下错误
![image](https://github.com/user-attachments/assets/47ffc52f-a489-4f0e-9d00-865ed668caf3)

【功能建议】
建议对非openai模型，如anthropic和gemini，增加一个配置项，允许非Openai模型的类Openai风格调用。

![image](https://github.com/user-attachments/assets/69b318f6-a28e-467b-b82b-c0d4b89ab386)

**Comment by satrong** [comment]
使用自定义 API 服务能解决吗？

**Comment by kinger310** [comment]
> 使用自定义 API 服务能解决吗？

不行。
比如选择anthropic，原来的代码只能用ChatAnthropic，这个调用的是`v1/messages`接口。但是我选的这两家AI三方服务，都是只支持`/chat/completions`接口。 所以我觉得应该添加一个配置项，能选择去兼容这种情况。

请satrong老师帮忙review下我PR哈

**Comment by satrong** [comment]
这个是我创建的自定义 API 服务，anthropic 的模型使用 openAI 的接口

![图片](https://github.com/user-attachments/assets/84bceec8-f759-4c8d-aa40-fd8d667c49a2)

**Comment by kinger310** [comment]
这样应该能解决，那PR我撤回吧
