### ISSUE TITLE
On the Apple iPhone, when the input method is activated on a dialog page, the page enlarges.

### ISSUE THREAD

**Issue by godoge** [sugarforever/chat-ollama#580]
On the dialogue page, the full page is initially displayed, but when the input method is activated for typing, the page enlarges, causing it to become incomplete. I hope this issue can be optimized.
![ec1b1a01ad8967bb284b6b95e2844d3](https://github.com/user-attachments/assets/42bf603c-5ce3-4eea-9f2d-c2f8bb62b2f3)
![49d1e3ffde7b0b15e738f99c2df531b](https://github.com/user-attachments/assets/0d5847cf-4e93-4c78-947c-50b635ee3e15)

**Comment by satrong** [comment]
I will try to fix it.

**Comment by satrong** [comment]
Fixed.

**Comment by godoge** [comment]
> Fixed. #583

Very thank you, I really like this tool!
