### ISSUE TITLE
docker搭建的chat-ollama，我在局域网访问。会建不了知识库

### ISSUE THREAD

**Issue by wenxiaoguo** [sugarforever/chat-ollama#602]
返回信息：request to http://peanutshell:8000/v1/rerank failed, reason: getaddrinfo ENOTFOUND peanutshell
![图像2024-12-23 07 35](https://github.com/user-attachments/assets/e7be267e-d3d6-4564-bc44-fc9df59f98c3)

具体信息：Mac mini M2 丐版docker拉取的，另一台笔记本电脑访问192.168.0.102:3000。可以聊天。但是创建不了知识库。

**Comment by sugarforever** [comment]
是用的docker-compose.yaml启动的吗？能确认peanutshell容器正常运行吗？

https://github.com/sugarforever/peanut-shell?tab=readme-ov-file#how-to-use
参考这个文档看看peanutshell是否正常工作。

**Comment by wenxiaoguo** [comment]
> 是用的docker-compose.yaml启动的吗？能确认peanutshell容器正常运行吗？
> 
> 
> 
> https://github.com/sugarforever/peanut-shell?tab=readme-ov-file#how-to-use
> 
> 参考这个文档看看peanutshell是否正常工作。

**Comment by wenxiaoguo** [comment]
我是在docker软件里，启动容器的。我回家用docker-compose up -d这个命令启动。感谢作者大大。

**Comment by sugarforever** [comment]
> 我是在docker软件里，启动容器的。我回家用docker-compose up -d这个命令启动。感谢作者大大。

用docker compose up -d能正常启动并使用吗？

**Comment by wenxiaoguo** [comment]
可以了，谢谢

**Comment by wenxiaoguo** [comment]
今天有网了。从新拉取了一次 谢谢
已经能使用了

**Comment by sugarforever** [comment]
有问题随时招呼。这个issue我就先关了。
