### ISSUE TITLE
刪除知識庫時，需不需要從 Chroma 資料庫中刪除不再使用的 Collection

### ISSUE THREAD

**Issue by Jacky97s** [sugarforever/chat-ollama#65]

**Comment by sugarforever** [comment]
需要的。感谢反馈。目前只从SQLite中删除了记录。

有兴趣开个合并请求解决这个问题吗？

**Comment by Jacky97s** [comment]
目前對 chromadb 的操作尚未熟悉，無法提供協助

**Comment by sugarforever** [comment]
> 目前對 chromadb 的操作尚未熟悉，無法提供協助

没事。这个问题已经在一个进行中的PR解决。晚上就会发布。

**Comment by sugarforever** [comment]
资料库的删除目前会同时清理向量数据集合与Redis存储。
