### ISSUE TITLE
Custom OpenAI URL

### ISSUE THREAD

**Issue by richwu** [sugarforever/chat-ollama#66]
目前OpenAI API 访问的路径是默认的URL，是吗？ 我希望能指定OpenAI为国内中转的URL该如何设置呢？谢谢

**Comment by sugarforever** [comment]
好的。这个需求尽快会实现。

**Comment by richwu** [comment]
期待中。。。

**Comment by sugarforever** [comment]
https://github.com/sugarforever/chat-ollama/pull/72 已完成自定义baseURL的支持。
