### ISSUE TITLE
能否支持gemini API

### ISSUE THREAD

**Issue by gallexy** [sugarforever/chat-ollama#70]
openai和anthropic经常封号，还是google的api用起来更方便

**Comment by sugarforever** [comment]
可以。周末给加上

**Comment by wgong** [comment]
> openai和anthropic经常封号，还是google的api用起来更方便

my openai account was closed, vote for google-api too, Thanks

**Comment by kaikanertan** [comment]
> 可以。周末给加上

希望可以早日完成。

**Comment by sugarforever** [comment]
@kaikanertan @wgong @gallexy 久等了。Google Gemni 1.0 模型的支持已经加上 - https://github.com/sugarforever/chat-ollama/pull/180

请拉取最新的代码或者docker image。目前Google API只支持1.0的模型，因此ChatOllama也只能使用1.0的Gemini模型。等API支持1.5，ChatOllama会及时更新。
