### ISSUE TITLE
Add chat-ollama to ollama community integration

### ISSUE THREAD

**Issue by wgong** [sugarforever/chat-ollama#78]
Following the short user-guide in README, I was able to run chat-ollama locally.
chat-ollama is a very nice web-UI for Ollama, 
- its UX design is intuitive and easy to use, 
- its knowledge-base feature is especially valuable.

I highly recommend to add `chat-ollama` to Ollama Community Integrations section to benefit more Ollama users

![image](https://github.com/sugarforever/chat-ollama/assets/329928/219a015a-1e42-469d-9881-d2e8a70448d4)

**Comment by ChenDaDong** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by sugarforever** [comment]
> Following the short user-guide in README, I was able to run chat-ollama locally. chat-ollama is a very nice web-UI for Ollama,
> 
> * its UX design is intuitive and easy to use,
> * its knowledge-base feature is especially valuable.
> 
> I highly recommend to add `chat-ollama` to Ollama Community Integrations section to benefit more Ollama users
> 
> ![image](https://private-user-images.githubusercontent.com/329928/313469958-219a015a-1e42-469d-9881-d2e8a70448d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODA0ODAsIm5iZiI6MTcxMDc4MDE4MCwicGF0aCI6Ii8zMjk5MjgvMzEzNDY5OTU4LTIxOWEwMTVhLTFlNDItNDY5ZC05ODgxLWQyZThhNzA0NDhkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxNjQzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmZmZmQzYjgyNTNhOWE4NzVkMWFkMDQ5OTAwODc0Yzk0MjRiMmZjYjg0NWVjNzFhMmZjYTRmM2I4ZjExY2VmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VNUcf-N94-SVcYfQHPfKEWc74H-ZO3AADWC8XJTmslI)

Thanks for the suggestion. Let me know if you can help reach out the Ollama team.

**Comment by wgong** [comment]
https://github.com/ollama/ollama/pull/3421

**Comment by satrong** [comment]
已经能看到了

![图片](https://github.com/sugarforever/chat-ollama/assets/5283258/fb90b34f-0516-4998-841d-5c5ce2f13f00)

**Comment by sugarforever** [comment]
Thanks everyone.
