### ISSUE TITLE
如何远程访问chat-ollama?

### ISSUE THREAD

**Issue by gallexy** [sugarforever/chat-ollama#8]
我试了修改nuxt.config.ts 和 package.json好像都没用啊
nuxt.config.ts
export default defineNuxtConfig({
  server: {
    host: '0.0.0.0',
    port: 8080
  }, 
  devtools: { enabled: true },
  modules: [
    '@nuxt/ui' 
  ]
})

**Comment by xiaojiegogogo** [comment]
我不知道为啥一直503

**Comment by gallexy** [comment]
更新版本后解决了
