### ISSUE TITLE
只能用localhost:3000或者127.0.0.1:3000，如何配置使用IP地址:3000访问？

### ISSUE THREAD

**Issue by TianxuHuang** [sugarforever/chat-ollama#80]
使用Ubuntu系统安装部署ollama和chat-ollama，能够正常运行，但只能用localhost:3000或者127.0.0.1:3000，如何配置使用IP地址:3000访问？

**Comment by wgong** [comment]
> 使用Ubuntu系统安装部署ollama和chat-ollama，能够正常运行，但只能用localhost:3000或者127.0.0.1:3000，如何配置使用IP地址:3000访问？

[ngrok](https://ngrok.com/) allows one to expose localhost to internet, I believe free-tier can have 1 public IP at a time

**Comment by satrong** [comment]
@TianxuHuang  你说的 ip 是局域网 ip 吗？如果是，可以参考这个 pr #85

**Comment by TianxuHuang** [comment]
支持IP访问：
cd chat-ollama
vi nuxt.config.ts
添加以下代码：
`,
  devServer: {
    host: '0.0.0.0',
  },`
nuxt.config.ts完整代码：
`// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: [
    '@nuxt/ui',
    '@vueuse/nuxt',
  ],
  devServer: {
    host: '0.0.0.0',
  },
})
`

**Comment by satrong** [comment]
嗯，我这个 pr 就是这么改的，等合并

**Comment by sugarforever** [comment]
> 使用Ubuntu系统安装部署ollama和chat-ollama，能够正常运行，但只能用localhost:3000或者127.0.0.1:3000，如何配置使用IP地址:3000访问？

假设你有IP 1.2.3.4，可以按如下方式指定dev server的监听IP

```
HOST=1.2.3.4 pnpm run dev
```

Nuxt 3支持通过HOST变量来指定监听端口 - https://nuxtjs.org/faq/host-port 。
