### ISSUE TITLE
聊天界面发送后没有响应

### ISSUE THREAD

**Issue by ljl3937** [sugarforever/chat-ollama#9]
我安装运行后，.env配置都很正常，模型下载加载也都没有问题，但是在chat界面发送消息后，没有任何回复，send一直在转圈，可能的原因会是什么？应该如何排查问题呢？
![image](https://github.com/sugarforever/chat-ollama/assets/6604219/0b8c2408-cd8e-4599-a3bb-7a38c1436949)

**Comment by satrong** [comment]
等 #7 合并了应该就可以了

**Comment by sugarforever** [comment]
@satrong 感谢PR。合并了。

@ljl3937 拉取一下最新的版本测试一下吧。

**Comment by ljl3937** [comment]
> @satrong 感谢PR。合并了。
> 
> @ljl3937 拉取一下最新的版本测试一下吧。

谢谢！响应太及时了！

**Comment by sugarforever** [comment]
> > @satrong 感谢PR。合并了。
> > @ljl3937 拉取一下最新的版本测试一下吧。
> 
> 谢谢！响应太及时了！

🎆
